### ISSUE TITLE
Unable to access API server on localhost

### ISSUE THREAD

**Issue by paulelliott** [ember-fastboot/ember-cli-fastboot#127]
I'm trying to run my ember app against an API server running on my local machine and am getting an error.

```
Error while processing route: index Ember Data Request GET http://localhost:3000/api/path returned a 0
Payload (Empty Content-Type)
Error: connect ECONNREFUSED 127.0.0.1:3000
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14) Error: Ember Data Request GET http://localhost:3000/api/path returned a 0
```

The target server is rails 4.2.5.1 and works fine against the ember app without fastboot enabled.

**Comment by dbbk** [comment]
I'm also having this issue. Any ideas?

**Comment by danmcclain** [comment]
What port is the rails app on? How is the ember app configured with regards to the above request? The Ajax request you're making is pointed to your fastboot server currently

**Comment by danmcclain** [comment]
Please comment if you are having this issue still

**Comment by adityasingh-ruckus** [comment]
I'm also facing the same issue. No idea why.

**Comment by danmcclain** [comment]
@adityasingh-ruckus can you provide more details? How are you attempting to hit your API?

**Comment by adityasingh-ruckus** [comment]
Thanks for reaching out @danmcclain 

My APIs are hosted on my local server, and I can validate the response using HTTPRequester  (Firefox add-on). However, when I try to send an API request using the browser, I get this error:-

Error while processing route: allprofiles.index
Ember Data Request GET http://localhost:5000/thisprofiles returned a 0
Payload (Empty Content-Type)

EmberError@http://localhost:4200/assets/vendor.js:26672:15
AdapterError@http://localhost:4200/assets/vendor.js:71016:5 


Here is how my JSONAdapter looks:-

export default JSONAPIAdapter.extend({
    host:'http://localhost:5000',
    headers:{
        'Authentication': 'my_auth_key',
        'Content-Type': ' application/json',
        'Access-Control-Allow-Origin': '*'
    }
});

**Comment by danmcclain** [comment]
Does your API get the proper request from fastboot? Are you on the latest beta of ember-cli-fastboot?

**Comment by adityasingh-ruckus** [comment]
I haven't installed fastboot. I had installed mirage and I thought once the APIs were ready,  a simple JSONAdapter would do. This is the first time I am using ember cli so there might be something which I have missed.

**Comment by danmcclain** [comment]
This is the fastboot repo, the fact that you are seeing this issue without fastboot means it may be an ember data issue

**Comment by jaiminvaja-cue** [comment]
@danmcclain 

I am using fastboot, it is working fine with static data and auth pages where I don't need authentication.

But it has issue when an API needs Authorization.

```
Error while processing route: task Ember Data Request GET http://embertaskapi.test/api/tasks returned a 401
Payload (application/json)
[object Object] Error: Ember Data Request GET http://embertaskapi.test/api/tasks returned a 401
Payload (application/json)
[object Object]
    at ErrorClass.AdapterError (/tmp/broccoli-14672NmFqyPFKCSXO/out-218-broccoli_merge_trees/assets/addon-tree-output/ember-data/-private.js:6175:1)
    at new ErrorClass (/tmp/broccoli-14672NmFqyPFKCSXO/out-218-broccoli_merge_trees/assets/addon-tree-output/ember-data/-private.js:6203:1)
    at Class.handleResponse (/tmp/broccoli-14672NmFqyPFKCSXO/out-218-broccoli_merge_trees/assets/addon-tree-output/ember-data/adapters/rest.js:801:1)
    at ajaxError (/tmp/broccoli-14672NmFqyPFKCSXO/out-218-broccoli_merge_trees/assets/addon-tree-output/ember-data/adapters/rest.js:1093:1)
    at ajaxErrorHandler (/tmp/broccoli-14672NmFqyPFKCSXO/out-218-broccoli_merge_trees/assets/addon-tree-output/ember-data/adapters/rest.js:1139:1)
    at Object.hash.error (/tmp/broccoli-14672NmFqyPFKCSXO/out-218-broccoli_merge_trees/assets/addon-tree-output/ember-data/adapters/rest.js:884:1)
    at fire (/var/www/html/hands-on-ember/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.fireWith (/var/www/html/hands-on-ember/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.fire [as reject] (/var/www/html/hands-on-ember/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at onError (/var/www/html/hands-on-ember/node_modules/najax/lib/najax.js:208:9)
    at dataHandler (/var/www/html/hands-on-ember/node_modules/najax/lib/najax.js:173:9)
    at IncomingMessage.<anonymous> (/var/www/html/hands-on-ember/node_modules/najax/lib/najax.js:198:9)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

Here is the error that I am facing.
Your help will be highly appreciated.

Thanks,
