### ISSUE TITLE
running the example in win10 Broccoli call stack error

### ISSUE THREAD

**Issue by menriquez** [ember-fastboot/ember-cli-fastboot#149]
Trying to run the example on win10 is throwing an error..

```
C:\Users\marke\ember\github-fastboot-example>ember server
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [object Object] failed with:
RangeError: Maximum call stack size exceeded
    at new Error (native)
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at sync (C:\Users\marke\ember\github-fastboot-example\node_modules\ember-network\node_modules\broccoli-templater\node_modules\broccoli-stew\node_modules\broccoli-funnel\node_modules\mkdirp\index.js:71:13)
    at sync (C:\Users\marke\ember\github-fastboot-example\node_modules\ember-network\node_modules\broccoli-templater\node_modules\broccoli-stew\node_modules\broccoli-funnel\node_modules\mkdirp\index.js:77:24)
    at sync (C:\Users\marke\ember\github-fastboot-example\node_modules\ember-network\node_modules\broccoli-templater\node_modules\broccoli-stew\node_modules\broccoli-funnel\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\marke\ember\github-fastboot-example\node_modules\ember-network\node_modules\broccoli-templater\node_modules\broccoli-stew\node_modules\broccoli-funnel\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\marke\ember\github-fastboot-example\node_modules\ember-network\node_modules\broccoli-templater\node_modules\broccoli-stew\node_modules\broccoli-funnel\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\marke\ember\github-fastboot-example\node_modules\ember-network\node_modules\broccoli-templater\node_modules\broccoli-stew\node_modules\broccoli-funnel\node_modules\mkdirp\index.js:78:17)
    at sync (C:\Users\marke\ember\github-fastboot-example\node_modules\ember-network\node_modules\broccoli-templater\node_modules\broccoli-stew\node_modules\broccoli-funnel\node_modules\mkdirp\index.js:78:17)

The broccoli plugin was instantiated at:
undefined
```

**Comment by felixrieseberg** [comment]
Note to self: Maaaaybe fix this?

**Comment by tomdale** [comment]
This has been fixed by @stefanpenner. :) Please upgrade `ember-network` to 0.6.0 or later.

**Comment by menriquez** [comment]
thanks to everyone for the fast fix and attention to the issue...i really
look forward to working with this stack,



On Wed, Apr 6, 2016 at 5:21 PM, Tom Dale <notifications@github.com> wrote:

> This has been fixed by @stefanpenner <https://github.com/stefanpenner>.
> :) Please upgrade ember-network to 0.6.0 or later.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/ember-fastboot/ember-cli-fastboot/issues/149#issuecomment-206575423>
>



-- 

Mark Enriquez, Owner/Lead Developer
321.328.7301
