### ISSUE TITLE
`ember build` performance regression

### ISSUE THREAD

**Issue by danmcclain** [ember-fastboot/ember-cli-fastboot#159]
I'm seeing 50 second initial build, 25 second rebuilds with `ember-cli-fastboot`, when removing the addon, the builds are 6 and 3 seconds

**Comment by stefanpenner** [comment]
```
  broccoli-funnel:Funnel processFilters { in: '8222ms', filesFound: 98110, filesProcessed: 90048, inputPath: '/Users/stefanpenner/talks/jazoon/training/jazoon-gitboot/tmp/funnel-input_base_path-4UzjZcnr.tmp/0', destPath: '/Users/stefanpenner/talks/jazoon/training/jazoon-gitboot/tmp/funnel-output_path-RuJWGef5.tmp' }
```

It seems like a very expensive funnel was added, to the output of the app build. This will have to traverse all of bower_components etc. I recommend finding a more specific place to apply this funnel.

Although it would be nice for this sort of funnel to be largely free, and future iterations of funnel/broccoli will aim to accomplish this. For now, we must be careful to funnel across small trees

**Comment by stefanpenner** [comment]
https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L67-L73 are the filters in-question.

As per previous recommendations (and I believe @tomdale is on-board), we should not build a different app anyways, so dropping that should also be a good build perf boost.

**Comment by tomdale** [comment]
@stefanpenner confirm

**Comment by tomdale** [comment]
I think that this is next on my list after the ability to reload a running server.

**Comment by stefanpenner** [comment]
@tomdale nice, i think the two are related. Basically, the way I see it, during development why not just run 2 servers:

1. normal dev server
2. fastboot server on a second port (my guess is running them on the same port my be confusing? although... it may not be ...)

Anyways, when a rebuild happens, just FB should just start serving the new build.

In theory, if the `app` builds are nearly the same, this should be relatively painless, and give a pretty cool dev experience.

**Comment by danmcclain** [comment]
After merging #145, I am seeing further regressions, one that causes the build process to crash by exhausting the memory for the process

```
╭─dan@Tron  ~/code/face-web ‹2.2.0› ‹dm-fastboot*›
╰─$ ember build -prod
version: 2.4.2
Building(node) warning: possible EventEmitter memory leak detected. 11 drain listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:665:33)
    at Stream.pipe (stream.js:45:8)
    at new UI (/Users/dan/code/face-web/node_modules/ember-cli/lib/ui/index.js:48:21)
    at ensureUI (/Users/dan/code/face-web/node_modules/ember-cli/lib/models/project.js:690:10)
    at Function.Project.closestSync (/Users/dan/code/face-web/node_modules/ember-cli/lib/models/project.js:594:12)
    at EmberApp._initProject (/Users/dan/code/face-web/node_modules/ember-cli/lib/broccoli/ember-app.js:135:45)
    at new EmberApp (/Users/dan/code/face-web/node_modules/ember-cli/lib/broccoli/ember-app.js:81:8)
    at module.exports (/Users/dan/code/face-web/ember-cli-build.js:28:13)
    at FastBootBuild.toTree (/Users/dan/code/face-web/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-build.js:67:41)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:665:33)
    at Stream.pipe (stream.js:79:8)
    at new UI (/Users/dan/code/face-web/node_modules/ember-cli/lib/ui/index.js:48:21)
    at ensureUI (/Users/dan/code/face-web/node_modules/ember-cli/lib/models/project.js:690:10)
    at Function.Project.closestSync (/Users/dan/code/face-web/node_modules/ember-cli/lib/models/project.js:594:12)
    at EmberApp._initProject (/Users/dan/code/face-web/node_modules/ember-cli/lib/broccoli/ember-app.js:135:45)
    at new EmberApp (/Users/dan/code/face-web/node_modules/ember-cli/lib/broccoli/ember-app.js:81:8)
    at module.exports (/Users/dan/code/face-web/ember-cli-build.js:28:13)
    at FastBootBuild.toTree (/Users/dan/code/face-web/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-build.js:67:41)
(node) warning: possible EventEmitter memory leak detected. 11 close listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at WriteStream.addListener (events.js:239:17)
    at WriteStream.Readable.on (_stream_readable.js:665:33)
    at Stream.pipe (stream.js:101:8)
    at new UI (/Users/dan/code/face-web/node_modules/ember-cli/lib/ui/index.js:48:21)
    at ensureUI (/Users/dan/code/face-web/node_modules/ember-cli/lib/models/project.js:690:10)
    at Function.Project.closestSync (/Users/dan/code/face-web/node_modules/ember-cli/lib/models/project.js:594:12)
    at EmberApp._initProject (/Users/dan/code/face-web/node_modules/ember-cli/lib/broccoli/ember-app.js:135:45)
    at new EmberApp (/Users/dan/code/face-web/node_modules/ember-cli/lib/broccoli/ember-app.js:81:8)
    at module.exports (/Users/dan/code/face-web/ember-cli-build.js:28:13)
    at FastBootBuild.toTree (/Users/dan/code/face-web/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-build.js:67:41)

<--- Last few GCs --->
<--- Last few GCs --->

  234264 ms: Mark-sweep 1369.9 (1456.7) -> 1369.5 (1456.7) MB, 1198.3 / 0 ms [allocation failure] [GC in old space requested].
  235495 ms: Mark-sweep 1369.5 (1456.7) -> 1369.4 (1456.7) MB, 1230.9 / 0 ms [allocation failure] [GC in old space requested].
  236704 ms: Mark-sweep 1369.4 (1456.7) -> 1369.4 (1456.7) MB, 1209.0 / 0 ms [last resort gc].
  237943 ms: Mark-sweep 1369.4 (1456.7) -> 1369.4 (1456.7) MB, 1238.4 / 0 ms [last resort gc].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x34741af37399 <JS Object>
    1: join [path.js:~475] [pc=0x393f65963743] (this=0xdf33274eb71 <an Object with map 0x25832962fef1>)
    2: arguments adaptor frame: 3->0
    3: loadNodeModulesSync(aka loadNodeModulesSync) [/Users/dan/code/face-web/node_modules/ember-cli/node_modules/resolve/lib/sync.js:77] [pc=0x393f5b3e8074] (this=0x34741af04131 <undefined>,x=0x31fa36b047f1 <String[15]: ember-cli-qunit>,start=0x2829374368...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
[1]    16640 abort      ember build -prod
```

**Comment by stefanpenner** [comment]
#node how does it work :(

**Comment by danmcclain** [comment]
I can get the project to build with 974d3228251128112446cc8cec62e11edf32ed40

**Comment by danmcclain** [comment]
More information: I was able to hit the out of memory error in the project with https://github.com/ember-fastboot/ember-cli-fastboot/commit/974d3228251128112446cc8cec62e11edf32ed40 when I had `ember-cli-fastboot` linked to `ember-fastboot-server`. I don't think the symlink is the issue, but the fact that more files are pulled in (since there is no (potential) de-duping of modules when symlinking)

**Comment by ludalex** [comment]
Having the exact same issue with my project. Was able to build as well with https://github.com/ember-fastboot/ember-cli-fastboot/commit/974d3228251128112446cc8cec62e11edf32ed40.

**Comment by stefanpenner** [comment]
https://github.com/ember-fastboot/ember-cli-fastboot/pull/356 should address this, and will be part of fastboot >= 1.0.0-rc1
