### ISSUE TITLE
Error: Use of const in strict mode.

### ISSUE THREAD

**Issue by jaijaz** [ember-fastboot/ember-cli-fastboot#193]
I have a brand new ember app following the FastBoot QuickStart .
```
DEBUG: -------------------------------
ember.debug.js:6440 DEBUG: Ember      : 2.5.1
ember.debug.js:6440 DEBUG: Ember Data : 2.5.2
ember.debug.js:6440 DEBUG: jQuery     : 2.2.3
ember.debug.js:6440 DEBUG: -------------------------------
VM413:87 Ember Inspector Active
```

Running `ember server` runs the app perfectly. However when I try running the FastBoot server `ember fastboot --serve-assets` I get this error:
```
Built project successfully. Stored in "dist".
Installing FastBoot npm dependencies
/Users/jaiivarsson/Code/jaiivarsson-fastboot/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/index.js:3
const FastBoot = require('fastboot');
^^^^^
Use of const in strict mode.
/Users/jaiivarsson/Code/jaiivarsson-fastboot/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/index.js:3
const FastBoot = require('fastboot');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/jaiivarsson/Code/jaiivarsson-fastboot/node_modules/ember-cli-fastboot/lib/commands/fastboot.js:28:34
    at lib$rsvp$$internal$$tryCatch (/Users/jaiivarsson/Code/jaiivarsson-fastboot/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/jaiivarsson/Code/jaiivarsson-fastboot/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1048:17)
```

My node version is node `v0.12.7`

Not sure what other details you might need?

**Comment by jasonmit** [comment]
https://github.com/ember-fastboot/fastboot-express-middleware/pull/1

**Comment by jasonmit** [comment]
https://github.com/ember-fastboot/fastboot

> FastBoot requires Node.js v4 or later.

**Comment by jaijaz** [comment]
OK thanks. I'll give that a try.

The homepage of www.ember-fastboot.com needs updating as it says `Node.js 0.10+`. Looked at the website repo to see if I could changed it and put through a but struggling to follow the content paths.

**Comment by jaijaz** [comment]
Upgrading Node worked.

Thanks.
