### ISSUE TITLE
Syntax Error caused by [object Object]

### ISSUE THREAD

**Issue by Gaurav0** [ember-fastboot/ember-cli-fastboot#205]
Steps to reproduce:

```bash
git clone https://github.com/ember-cli/ember-twiddle.git
cd ember-twiddle
git fetch origin pull/438/head:fastboot_test
git checkout fastboot_test
ember serve (Note this works)
ember fastboot --serve-assets (Breaks with Syntax Error: unexpected identifier
```

Here is the full stacktrace:
```
gmunjal@helpdesks-MacBook-Pro-3:~/code/ember-twiddle (fastboot_test)$ DEBUG=ember-cli-fastboot:* ember fastboot --serve-assets
bootstrap-sassy config: some JS loaded [dropdown,collapse], glyphicons enabled
bootstrap-sassy config: no JS enabled [FastBoot], glyphicons enabled
Built project successfully. Stored in "dist".
Installing FastBoot npm dependencies
Unexpected identifier
SyntaxError: Unexpected identifier
    at Sandbox.VMSandbox.eval (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/vm-sandbox.js:13:20)
    at EmberApp.retrieveSandboxedApp (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/ember-app.js:134:13)
    at new EmberApp (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/ember-app.js:47:21)
    at FastBoot._buildEmberApp (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/index.js:102:17)
    at new FastBoot (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/index.js:47:10)
    at fastbootExpressMiddleware (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/index.js:24:16)
    at /Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/lib/commands/fastboot.js:32:26
    at lib$rsvp$$internal$$tryCatch (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/gmunjal/code/ember-twiddle/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/rsvp.js:1019:11)
```

And here are the first lines of dist/fastboot/vendor.js:
```javascript
/* jshint ignore:start */

window.EmberENV = {"FEATURES":{}};
var runningTests = false;



/* jshint ignore:end */

;[object Object]
;var loader, define, requireModule, require, requirejs;

(function(global) {
  'use strict';

  // Save off the original values of these globals, so we can restore them if someone asks us to
  var oldGlobals = {
//...
```

I think the Syntax Error is coming from the `[object Object]` in the generated javascript

**Comment by stefanpenner** [comment]
> ;[object Object]

looks like something is accidentally coercing an object it expects to be a string...

**Comment by danmcclain** [comment]
Can you try removing addons to see which one is causing this issue?

**Comment by Gaurav0** [comment]
Yes, it's the babel polyfill.

**Comment by Gaurav0** [comment]
Solution (for those who need it):

Disable the `includePolyfill` when `process.env.EMBER_CLI_FASTBOOT` is true and include the polyfill as follows:

```javascript
if (process.env.EMBER_CLI_FASTBOOT) {
    var b = browserify();
    b.add(require.resolve('babel/polyfill'));
    b.bundle(function(err, buf) {
      fs.writeFileSync('vendor/polyfill.js', buf);
    });
    app.import('vendor/polyfill.js', { prepend: true });
  }
``` 

If anyone has an idea how to make that faster, please let me know.
