### ISSUE TITLE
_emberMetalProperty_get.get(...).getURL is not a function

### ISSUE THREAD

**Issue by tschoartschi** [ember-fastboot/ember-cli-fastboot#223]
When there is an error in an instance-initializer a very unhelpful exception is thrown. You will get the following stacktrace: 

```
TypeError: _emberMetalProperty_get.get(...).getURL is not a function
    at [object Object].<anonymous> (.../fastboot-tryout/dist/fastboot/vendor.js:37104:60)
    at Descriptor.ComputedPropertyPrototype.get (.../fastboot-tryout/dist/fastboot/vendor.js:24406:28)
    at Object.get (.../fastboot-tryout/dist/fastboot/vendor.js:30060:19)
    at [object Object]._emberApplicationSystemEngineInstance.default.extend.getURL (.../fastboot-tryout/dist/fastboot/vendor.js:14143:38)
    at Result._finalizeMetadata (.../fastboot-tryout/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/result.js:74:25)
    at Result._finalize (.../fastboot-tryout/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/result.js:64:12)
    at .../fastboot-tryout/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/lib/ember-app.js:225:26
    at tryCatch (.../fastboot-tryout/dist/fastboot/vendor.js:61543:14)
    at invokeCallback (.../fastboot-tryout/dist/fastboot/vendor.js:61558:15)
    at publish (.../fastboot-tryout/dist/fastboot/vendor.js:61526:9)
    at .../fastboot-tryout/dist/fastboot/vendor.js:41428:7
    at Queue.invokeWithOnError (.../fastboot-tryout/dist/fastboot/vendor.js:10468:18)
    at Object.Queue.flush (.../fastboot-tryout/dist/fastboot/vendor.js:10523:11)
    at Object.DeferredActionQueues.flush (.../fastboot-tryout/dist/fastboot/vendor.js:10331:17)
    at Object.Backburner.end (.../fastboot-tryout/dist/fastboot/vendor.js:10686:25)
    at [object Object]._onTimeout (.../fastboot-tryout/dist/fastboot/vendor.js:11252:18)
```

The real error is kind of "swallowed" and very very hard to find. What happens behind the scene is the following:

The error is kind of caught in a promise and the reject callback in ```rsvp/-internal``` is called. This happens in ```initializePromise``` with ```reject(promise, e)``` for more details see the screenshot of the stack trace. At this point the correct error is "caught"

![stacktrace](https://cloud.githubusercontent.com/assets/1695329/16393600/b4ca5df2-3cb1-11e6-82ae-e38a795edc93.jpg)

If you continue to step through the program there is going on a lot behind the scenes, like flushing the queues etc. At the end ```fastboot/lib/result.js``` calls the ```_finalize``` method and then ```_finalizeMetadata```. ```_finalizeMetadata``` calls ```instance.getURL()``` and then for some reason getURL does not work because it is undefined. If there is no error during instance initializing then the stack trace looks almost the same and ```instance.getURL()``` works as expected. 

The main problem with this issue is, that the stack trace to ```_emberMetalProperty_get.get(...).getURL is not a function``` is totally misleading. I digged around in all of the dependencies because the stack trace never pointed to my own source files and I was really lost. It was just coincidence that I had a break point in ```rsvp/-internal``` at the ```reject``` callback. I'm not sure if it is a bug but it makes getting fastboot to work really hard.

Steps to reproduce:

```shell
mkdir fastboot-tryout
cd fastboot-tryout/
ember init
ember install ember-cli-fastboot
ember g instance-initializer make-fastboot-fail
vi app/instance-initializers/make-fastboot-fail.js 
```
write something like the following into make-fastboot-fail.js
```javascript
export function initialize(/* appInstance */) {
  // appInstance.inject('route', 'foo', 'service:foo');
  if(undef.makeItFail) {
    return;
  }
  // DO SOMETHING
}

export default {
  name: 'make-fastboot-fail',
  initialize
};
```
Then execute the following commands:

```shell
ember fastboot
curl http://localhost:3000/
```
After that you should see the exception from the beginning of my post. For more details I attached my package.json and bower.json

[package.txt](https://github.com/ember-fastboot/ember-cli-fastboot/files/335718/package.txt)
[bower.txt](https://github.com/ember-fastboot/ember-cli-fastboot/files/335719/bower.txt)

**Comment by tschoartschi** [comment]
@IAmJulianAcosta it seems my issue is similar to yours (#209). Do you think so too?

**Comment by IAmJulianAcosta** [comment]
Yes, is a very similar issue.

**Comment by tschoartschi** [comment]
@IAmJulianAcosta do you have an idea how we could create a pull request which fixes this problem? I'm still not sure what our exact problem is. I think the problem is that the stack trace is misleading and that an error which is caught still causes a crash later on. Do you think it is better to first prevent the app from crashing at all and then focusing on the stack trace?

**Comment by IAmJulianAcosta** [comment]
I have to recreate the problem again to fix it, but I damaged the VM where I was working with fastboot. Fortunately I documented well this problem and I'll be able to recreate again easily. I'll get in touch with you in ember chat.

**Comment by jasonmit** [comment]
I spent some time stepping through this today because I also ran into it porting an app.

When an exceptions occurs within an instance initializer, the application instance never finishes setting up and there for `location` is still a string, "none", and not the expected `Ember.NoneLocation` instance.

Where this begins to unravel is in inside the [lib/ember-app visit method](https://github.com/ember-fastboot/fastboot/blob/master/lib/ember-app.js#L222).  The error is handled by assigning it to `result.error` and immediately followed by [invoking `result._finalize`](https://github.com/ember-fastboot/fastboot/blob/master/lib/ember-app.js#L225) which in [turn calls `getURL`](https://github.com/ember-fastboot/fastboot/blob/71f982e43a7d6f02d3361fb0db95e782c2af7373/lib/result.js#L74) on the string since the router never materialized `location` into an object.

For those stuck, I suggest putting a breakpoint here or logging to the console [`error`](https://github.com/ember-fastboot/fastboot/blob/master/lib/ember-app.js#L224).  That will give the error that you're after.

I'm unsure on the right way to go about fixing this, either we type check before calling getURL and default to a route in the failcase or we ensure the router is finalized a bit earlier.

**Comment by tschoartschi** [comment]
> For those stuck, I suggest putting a breakpoint here or logging to the console error. That will give the error that is being swallowed.

This is exactly what I've been doing 😉 I think the problem is, that it is super hard to debug (if you don't know all the internals of Ember and Fastboot). I got stuck setting up fastboot for about a week because I always thought it is a problem with Ember Simple Auth. So I was searching for the bug in a spot where it never occurred. 

I tried to create a pull request but I'm also not sure how to fix this. Especially because I'm not an expert with all the Ember and Fastboot internals.

**Comment by jasonmit** [comment]
https://github.com/ember-fastboot/fastboot/pull/71 fixes the issue

**Comment by steffansluis** [comment]
What is the current state of this? I seem to be running into it while switching to fastboot.

**Comment by oskarrough** [comment]
Also seeing this in my acceptance tests as of Ember 2.13.2 but I am not using FastBoot.

**Comment by oa495** [comment]
Same. Running in acceptance tests for ember 2.12.1 but not using FastBoot.

**Comment by PriyangaSG** [comment]
Same issue while running unit tests for ember 2.14

**Comment by kratiahuja** [comment]
Can someone provide a minimal reproduction?

**Comment by cahyowhy** [comment]
Same Issue here.... Running in acceptance tests for ember 2.17

**Comment by lolmaus** [comment]
I've been having this error in acceptance tests, unrelated to FastBoot.

The cause of the problem was that I was missing `await` for `visit()`.

**Comment by amk221** [comment]
I've been having this error in model tests, unrelated to FastBoot

@lolmaus's unfortunately suggested fix isn't applicable for my case.

**Comment by lolmaus** [comment]
@amk221 That's weird. Model tests are integration tests, I assume the URL should not be involved in any way.

Can you post your test to https://gist.github.com ?

**Comment by amk221** [comment]
https://github.com/amk221/-ember-data-geturl-not-a-function/commit/3ab9aa7d527cac88d126fdf81d7b87f0a13c02e4

**Comment by lolmaus** [comment]
@amk221 You have a number of issues with your test:
* Your test is async, but you're testing it as sync. It's necessary to add `await` like I suggested above.
* The `foo.bar` relationship in your payload fixture is empty, yet you're asserting that it's populated with `bar`.

I've filed a pull request addressing these and the test is green: https://github.com/amk221/-ember-data-geturl-not-a-function/pull/1

That said, the error `_emberMetalProperty_get.get(...).getURL is not a function` is extremely cryptic and indicates an inner problem with Ember and/or Ember Data. The happy path is fine, but a faulty state is not handled properly and the whole thing blows up instead of gracefully reporting the issue *where it actually happens*.

Metaphorically speaking the app should produce a gag reflex and refuse to swallow a large object. Instead, it swallows the object as if it's fine and dies from intestine blockage.

**Comment by amk221** [comment]
- Yes, that's just because I forgot, as the actual test is much more involved, and this is was a quick reproduction
- Yes, that is intentional, that is how the error is triggered.
