### ISSUE TITLE
Unexpected token init()

### ISSUE THREAD

**Issue by zion03** [ember-fastboot/ember-cli-fastboot#263]
Hello, after start `ember fastboot` recived exception

> /frontend/node_modules/ember-cli-fastboot/index.js:23
>   init() {
>       ^
> Unexpected token (
> SyntaxError: Unexpected token (
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Function.Addon.lookup (/frontend/node_modules/ember-cli/lib/models/addon.js:999:19)
>     at /frontend/node_modules/ember-cli/lib/models/addons-factory.js:47:38
>     at visit (frontend/node_modules/ember-cli/lib/utilities/DAG.js:23:3)
>     at DAG.topsort (frontend/node_modules/ember-cli/lib/utilities/DAG.js:137:7)
>

**Comment by zion03** [comment]
Looks like this error depends on node version, my current v4.5.0

**Comment by zion03** [comment]
Solved.
It was mistake in node versions:
`nodejs --version` --> v4.5
`node --version` --> 0.10
