### ISSUE TITLE
There was an error trying to run your application in FastBoot. (vanilla install)

### ISSUE THREAD

**Issue by brandensilva** [ember-fastboot/ember-cli-fastboot#283]
The following error pops up on a fresh install of ember + fastboot. I assume things aren't supposed to explode when doing simple text changes while fastboot is running.

```
There was an error trying to run your application in FastBoot.

This is usually caused by either your application code or an addon trying to access an API that isn't available in Node.js.
Based on the stack trace, it looks like the exception was generated in node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/src/ember-app.js on line 245.
The exception is probably coming from your app. Look at this file and line number to determine what is triggering the exception.

The full stack trace is:

Couldn't find /Users/bsilva/ember/fastsample/dist/package.json. You may need to update your version of ember-cli-fastboot.
Error: Couldn't find /Users/bsilva/ember/fastsample/dist/package.json. You may need to update your version of ember-cli-fastboot.
    at EmberApp.readPackageJSON (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/src/ember-app.js:245:13)
    at new EmberApp (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/src/ember-app.js:32:23)
    at FastBoot._buildEmberApp (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/src/index.js:102:17)
    at new FastBoot (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/node_modules/fastboot/src/index.js:47:10)
    at fastbootExpressMiddleware (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/fastboot-express-middleware/index.js:24:16)
    at /Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/lib/tasks/fastboot-server.js:33:71
    at tryCatch (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at publish (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:7)
    at flush (/Users/bsilva/ember/fastsample/node_modules/ember-cli-fastboot/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
```

_Dependencies_
![image](https://cloud.githubusercontent.com/assets/200190/19586681/bb7b6494-9714-11e6-9d2b-cfc7350c038c.png)
![image](https://cloud.githubusercontent.com/assets/200190/19586693/e6923f22-9714-11e6-8a74-55dfca611e94.png)

_Reproduce_
1. ember new [projectname]
2. ember install ember-cli-fastboot
3. ember generate route index
4. add a string above {{outlet}} in the generated index.hbs
5. ember fastboot --serve-assets
6. verify everything is work on localhost:3000. Should be good.
7. add another part to the string and hit save.
8. Explosions

**Comment by brandensilva** [comment]
I'm going to attempt to upgrade Ember to the latest and greatest point releases to see if that helps resolve this issue. The latest Fastboot seems to install ember 2.8.2 and ember-data 2.9.0 which I'm not sure if that would be the issue with the client operating slightly lower than that.

**Comment by danmcclain** [comment]
This is a known issue with watch, we have a fix in place, but the beta hasn't been updated just yet, see if master works fine for you, and there will be a new beta released very soon with this fix

**Comment by brandensilva** [comment]
Sounds great Dan. I'll check out master tomorrow and report back.

**Comment by danmcclain** [comment]
@brandensilva I released beta.11 yesterday that has the fix in it

**Comment by Blackening999** [comment]
```bash
There was an error trying to run your application in FastBoot.

This is usually caused by either your application code or an addon trying to access an API that isn't available in Node.js.
Based on the stack trace, it looks like the exception was generated in vm.js on line 53.
The exception is probably coming from your app. Look at this file and line number to determine what is triggering the exception.

The full stack trace is:

Unexpected token {
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/black/Work/My_Projects/project-fastboot/node_modules/fastboot/src/ember-app.js:12:22)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
```

**Comment by Blackening999** [comment]
@danmcclain

**Comment by Blackening999** [comment]
Work with Node v6.9.2. Will keep inside what I'm thinking about all of this :D 
Hope this will help others

**Comment by danmcclain** [comment]
How did you install fastboot for this app? I may have messed up the publishing of fastboot, it looks like the builds for previous versions of node for ES5 didn't happen

**Comment by Blackening999** [comment]
@danmcclain I did it directly from ember-fastboot site. You know, that nicely markupped tutorial :P 
App dies after any change made in .*js, switched name from tomdale to Blackening999 from example, and then it resurrects after full re-install of npm/bower../tmp/dist

**Comment by indieNik** [comment]
Any update on this issue?
==========================================
$ ember -v
ember-cli: 2.12.2
node: 6.9.5
os: win32 x64
==========================================
$ npm list ember-cli-fastboot version
ember-blog@0.0.0 D:\EmberProjects\ember-blog
`-- ember-cli-fastboot@1.0.0-beta.18
==========================================

**Comment by kratiahuja** [comment]
@indieNik Are you using `ember fastboot --serve-assets` to serve the app?

**Comment by kratiahuja** [comment]
Closing this. `ember s` should resolve the watch issue.

**Comment by brandensilva** [comment]
Work got the best of me, apologies for not reporting back! Thanks for your efforts guys it appears to be working now.
