### ISSUE TITLE
"EventDispatcher should never be instantiated in fastboot mode." in Ember 2.10

### ISSUE THREAD

**Issue by t4t5** [ember-fastboot/ember-cli-fastboot#295]
Upgrading my project to 2.10 resulted in this error message:

```
Ember FastBoot running at http://[::]:3000
2016-12-01T11:27:29.472Z 500 Unknown Error: Error: Assertion Failed: EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug.
    at assert (/my-project/dist/fastboot/vendor.js:16246:13)
    at Object.assert (/my-project/dist/fastboot/vendor.js:27182:34)
    at Class.init (/my-project/dist/fastboot/vendor.js:51429:19)
    at Class.superWrapper [as init] (/my-project/dist/fastboot/vendor.js:50174:22)
    at new Class (/my-project/dist/fastboot/vendor.js:45865:17)
    at Function.create (/my-project/dist/fastboot/vendor.js:46153:14)
    at instantiate (/my-project/dist/fastboot/vendor.js:12084:23)
    at lookup (/my-project/dist/fastboot/vendor.js:11921:17)
    at Object.lookup (/my-project/dist/fastboot/vendor.js:11840:14)
    at Class.lookup (/my-project/dist/fastboot/vendor.js:42312:33)
    at /my-project/dist/fastboot/vendor.js:17492:59
    at Class.init (/my-project/dist/fastboot/vendor.js:17502:9)
    at Class.superWrapper (/my-project/dist/fastboot/vendor.js:50174:22)
    at Class.init (/my-project/dist/fastboot/vendor.js:107076:19)
    at Class.superWrapper [as init] (/my-project/dist/fastboot/vendor.js:50174:22)
    at new Class (/my-project/dist/fastboot/vendor.js:45865:17)
    at Function.create (/my-project/dist/fastboot/vendor.js:46153:14)
    at Object.initialize (/my-project/dist/fastboot/ludu.js:9415:38)
    at /my-project/dist/fastboot/vendor.js:15110:21
    at Vertices.each (/my-project/dist/fastboot/vendor.js:13163:13)
    at Vertices.topsort (/my-project/dist/fastboot/vendor.js:13130:14)
    at DAG.topsort (/my-project/dist/fastboot/vendor.js:13075:24)
    at Class._runInitializer (/my-project/dist/fastboot/vendor.js:15125:13)
    at Class.runInstanceInitializers (/my-project/dist/fastboot/vendor.js:15108:12)
    at Class._bootSync (/my-project/dist/fastboot/vendor.js:13381:24)
    at /my-project/dist/fastboot/vendor.js:14793:30
    at initializePromise (/my-project/dist/fastboot/vendor.js:68754:5)
    at new Promise (/my-project/dist/fastboot/vendor.js:69239:31)
    at Class.boot (/my-project/dist/fastboot/vendor.js:14792:27)
    at buildAppInstance.then.appInstance (/my-project/node_modules/fastboot/src/ember-app.js:235:25)
    at tryCatch (/my-project/dist/fastboot/vendor.js:68706:12)
    at invokeCallback (/my-project/dist/fastboot/vendor.js:68718:13)
    at publish (/my-project/dist/fastboot/vendor.js:68689:7)
    at /my-project/dist/fastboot/vendor.js:48172:16
    at invokeWithOnError (/my-project/dist/fastboot/vendor.js:10881:16)
    at Object.flush (/my-project/dist/fastboot/vendor.js:10940:9)
    at Object.flush (/my-project/dist/fastboot/vendor.js:11064:15)
    at Object.end (/my-project/dist/fastboot/vendor.js:11134:23)
    at Timeout._onTimeout (/my-project/dist/fastboot/vendor.js:11700:16)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

This doesn't seem to happen when I create a new blank project, so I'm not sure where the issue lies exactly.

**Comment by Kuzirashi** [comment]
Can you paste your package.json to show your dependencies?

**Comment by t4t5** [comment]
Sure! It's a big one. :-)

```json
{
  "name": "ludu",
  "version": "2.0.0",
  "description": "Learn from each other.",
  "author": "Ludu",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "postinstall": "./script-postinstall.sh",
    "start": "./script-start.sh",
    "test": "./script-test.sh"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.12.0"
  },
  "author": "",
  "license": "MIT",
  "devDependencies": {
    "assert": "1.4.1",
    "bluebird": "3.4.1",
    "bower": "1.7.9",
    "broccoli-asset-rev": "^2.4.5",
    "ember-ajax": "^2.4.1",
    "ember-api-actions": "0.1.6",
    "ember-blur-up": "0.1.3",
    "ember-body-class": "0.3.9",
    "ember-browserify": "1.1.9",
    "ember-cli": "2.10.0",
    "ember-cli-accounting": "1.0.1",
    "ember-cli-app-version": "^2.0.0",
    "ember-cli-babel": "^5.1.7",
    "ember-cli-base64-converter": "https://github.com/Ludu/ember-cli-base64-converter",
    "ember-cli-build-notifications": "0.2.0",
    "ember-cli-component-pod": "0.1.0",
    "ember-cli-content-security-policy": "0.5.0",
    "ember-cli-dependency-checker": "^1.3.0",
    "ember-cli-document-title": "0.3.1",
    "ember-cli-dotenv": "1.2.0",
    "ember-cli-fastboot": "1.0.0-beta.13",
    "ember-cli-google-analytics": "1.5.0",
    "ember-cli-head": "0.0.7",
    "ember-cli-htmlbars": "^1.0.10",
    "ember-cli-htmlbars-inline-precompile": "^0.3.3",
    "ember-cli-imagemin": "0.4.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-jshint": "^2.0.1",
    "ember-cli-latex-maths": "0.4.0",
    "ember-cli-meta-tags": "2.0.0",
    "ember-cli-mirage": "0.2.0",
    "ember-cli-moment-shim": "2.2.1",
    "ember-cli-pace": "0.1.0",
    "ember-cli-photoswipe": "1.2.0",
    "ember-cli-qunit": "^3.0.1",
    "ember-cli-release": "^0.2.9",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-stripe": "0.4.0",
    "ember-cli-stylus": "https://github.com/Ludu/ember-cli-stylus#master",
    "ember-cli-test-loader": "^1.1.0",
    "ember-cli-uglify": "^1.2.0",
    "ember-click-outside": "0.1.3",
    "ember-component-css": "0.2.6",
    "ember-component-inbound-actions": "1.0.1",
    "ember-computed-decorators": "0.2.2",
    "ember-cookies": "git://github.com/t4t5/ember-cookies.git#patch-1",
    "ember-data": "^2.10.0",
    "ember-export-application-global": "^1.0.5",
    "ember-href-to": "1.9.0",
    "ember-i18n": "4.3.2",
    "ember-link-action": "0.0.35",
    "ember-load-initializers": "^0.5.1",
    "ember-moment": "6.1.0",
    "ember-resolver": "^2.0.3",
    "ember-truth-helpers": "1.2.0",
    "ember-websockets": "6.2.0",
    "ember-welcome-page": "^1.0.3",
    "ember-zeroclipboard": "https://github.com/Ludu/ember-zeroclipboard#master",
    "i": "0.3.5",
    "ivy-codemirror": "2.0.3",
    "liquid-fire": "0.26.5",
    "loader.js": "^4.0.10",
    "mocha": "3.0.2",
    "mock-socket": "6.0.1",
    "supertest": "2.0.0",
    "torii": "0.8.0"
  },
  "dependencies": {
    "autosize": "3.0.15",
    "basic-auth": "1.0.4",
    "cheerio": "0.22.0",
    "body-parser": "1.15.2",
    "colors": "1.1.2",
    "compression": "1.6.2",
    "cookie": "0.3.1",
    "cookie-parser": "1.4.3",
    "cors": "2.7.1",
    "dotenv": "2.0.0",
    "express": "4.14.0",
    "express-handlebars": "3.0.0",
    "fastboot-app-server": "1.0.0-rc.4",
    "forcedomain": "0.8.0",
    "forever": "0.15.2",
    "request": "2.75.0",
    "request-promise": "4.1.1",
    "heroku-node-settings": "1.0.2"
  },
  "fastbootDependencies": [
    "ember-ajax"
  ]
}
```

**Comment by danmcclain** [comment]
Are you still seeing this issue with the latest beta? Others have been using fastboot + 2.10 successfully, so I'm wondering if a specific addon is causing the issue

**Comment by t4t5** [comment]
@danmcclain Unfortunately yes, even after updating my dependencies again. :/ 

Here's more from the error log:

```bash
Error {
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  message: 'Assertion Failed: EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug.',
  name: 'Error',
  number: undefined,
  code: undefined }
2016-12-27T02:59:41.551Z 200 NOT OK /browse
Error: Can't set headers after they are sent.
    at SendStream.headersAlreadySent (/Users/Tristan/dev/Ludu/node_modules/send/index.js:361:13)
    at SendStream.send (/Users/Tristan/dev/Ludu/node_modules/send/index.js:572:10)
    at onstat (/Users/Tristan/dev/Ludu/node_modules/send/index.js:677:10)
    at FSReqWrap.oncomplete (fs.js:123:15)
2016-12-27T02:59:41.682Z RESILIENT MODE CAUGHT: Error: Assertion Failed: EventDispatcher should never be instantiated in fastboot mode. Please report this as an Ember bug.
    at assert (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:16268:13)
    at Object.assert (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:27196:34)
    at Class.init (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:51446:19)
    at Class.superWrapper [as init] (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:50189:22)
    at new Class (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:45879:17)
    at Function.create (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:46167:14)
    at instantiate (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:12104:23)
    at lookup (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:11941:17)
    at Object.lookup (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:11860:14)
    at Class.lookup (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:42326:33)
    at /Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:17515:59
    at Class.init (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:17525:9)
    at Class.superWrapper (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:50189:22)
    at Class.init (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:107185:19)
    at Class.superWrapper [as init] (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:50189:22)
    at new Class (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:45879:17)
    at Function.create (/Users/Tristan/dev/Ludu/dist/fastboot/vendor.js:46167:14)
    at Object.initialize (/Users/Tristan/dev/Ludu/dist/fastboot/ludu.js:9752:38)
```

If I go to `ludu.js:9752:38`, i stumble upon this code block:

```javascript
define('ludu/instance-initializers/fastboot/head', ['exports'], function (exports) {
  exports.initialize = initialize;

  function initialize(instance) {
    var renderer = instance.lookup('renderer:-dom');
    var componentFactory = instance._lookupFactory('component:head-layout');
    // explicitly set renderer & domhelper since we're in fastboot
    var component = componentFactory.create(instance.ownerInjection(), {
      renderer: renderer,
      _domHelper: renderer._dom
    });
    component.appendTo(renderer._dom.document.head);
  }

  exports['default'] = {
    name: 'head-fastboot',
    initialize: initialize
  };
});
```

So it seems like it might be a problem with the [Ember CLI Head addon](https://github.com/ronco/ember-cli-head)

**Comment by t4t5** [comment]
Turns out it was [Ember CLI meta tags](https://github.com/ronco/ember-cli-meta-tags) that needed to be updated. It's hard keeping track of all the addons sometimes. :)

**Comment by bcardarella** [comment]
@t4t5 we're seeing the same error after bringing in ember-cli-meta-tags, I'm on the latest (3.0.4) with the same error. Was there anything else you did to resolve?

**Comment by t4t5** [comment]
@bcardarella Sorry for such a late reply, but no, I don't think I did anything else. The error was caused by the addon. 

I guess the only way to find out the source of the error in your project is to "turn off" every dependency one after the other until the project starts working again. Would be nice if this could be made easier in Ember CLI!

**Comment by kpfefferle** [comment]
I am encountering this error again in Ember 2.11: https://github.com/ronco/ember-cli-meta-tags/issues/51

**Comment by briangonzalez** [comment]
For those joining late, upgrading `ember-cli-head` to 0.1.4 fixed this for me.

https://github.com/ronco/ember-cli-head/issues/18
