### ISSUE TITLE
Ember 2.10: TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by bjerh** [ember-fastboot/ember-cli-fastboot#299]
Hi. I'm getting this error having switched to Ember 2.10.0 from 2.9.something.

`
TypeError: Cannot read property 'prototype' of undefined
`

The line specified is located in the module shown below:

```
/* globals najax */
define("pentia-dk/initializers/fastboot/dom-helper-patches", ["exports"], function (exports) {
  /*globals Ember, URL*/
  exports["default"] = {
    name: "dom-helper-patches",

    initialize: function initialize(App) {
      // TODO: remove me
      Ember.HTMLBars.DOMHelper.prototype.protocolForURL = function (url) {
        var protocol = URL.parse(url).protocol;
        return protocol == null ? ':' : protocol;
      };

      // TODO: remove me https://github.com/tildeio/htmlbars/pull/425
      Ember.HTMLBars.DOMHelper.prototype.parseHTML = function (html) {
        return this.document.createRawHTMLSection(html);
      };
    }
  };
});
```

The specific line throwing the error is the following:

`Ember.HTMLBars.DOMHelper.prototype.protocolForURL = function (url) {`

Below is the full error message:

```
2016-12-08T12:02:25.780Z 500 Unknown Error: TypeError: Cannot read property 'prototype' of undefined
    at Object.initialize (C:\Projects\pentiadk\dist\fastboot\pentia-dk.js:1532:31)
    at C:\Projects\pentiadk\dist\fastboot\vendor.js:15767:23
    at Vertices.each (C:\Projects\pentiadk\dist\fastboot\vendor.js:13833:13)
    at Vertices.topsort (C:\Projects\pentiadk\dist\fastboot\vendor.js:13800:14)
    at DAG.topsort (C:\Projects\pentiadk\dist\fastboot\vendor.js:13745:24)
    at _emberRuntime.Namespace.extend._runInitializer (C:\Projects\pentiadk\dist\fastboot\vendor.js:15795:13)
    at _emberRuntime.Namespace.extend.runInitializers (C:\Projects\pentiadk\dist\fastboot\vendor.js:15756:12)
    at _emberApplicationSystemEngine.default.extend._bootSync (C:\Projects\pentiadk\dist\fastboot\vendor.js:14965:14)
    at _emberApplicationSystemEngine.default.extend.boot (C:\Projects\pentiadk\dist\fastboot\vendor.js:14932:14)
    at EmberApp.buildAppInstance (C:\Projects\pentiadk\node_modules\fastboot\src\ember-app.js:173:21)
    at EmberApp.visit (C:\Projects\pentiadk\node_modules\fastboot\src\ember-app.js:213:17)
    at FastBoot.visit (C:\Projects\pentiadk\node_modules\fastboot\src\index.js:70:22)
    at C:\Projects\pentiadk\node_modules\fastboot-express-middleware\index.js:32:14
    at Layer.handle [as handle_request] (C:\Projects\pentiadk\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Projects\pentiadk\node_modules\express\lib\router\route.js:131:13)
    at Route.dispatch (C:\Projects\pentiadk\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Projects\pentiadk\node_modules\express\lib\router\layer.js:95:5)
    at C:\Projects\pentiadk\node_modules\express\lib\router\index.js:277:22
    at param (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:349:14)
    at param (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:271:10)
    at expressInit (C:\Projects\pentiadk\node_modules\express\lib\middleware\init.js:33:5)
    at Layer.handle [as handle_request] (C:\Projects\pentiadk\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:312:13)
    at C:\Projects\pentiadk\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:271:10)
    at query (C:\Projects\pentiadk\node_modules\express\lib\middleware\query.js:44:5)
    at Layer.handle [as handle_request] (C:\Projects\pentiadk\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:312:13)
    at C:\Projects\pentiadk\node_modules\express\lib\router\index.js:280:7
    at Function.process_params (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:330:12)
    at next (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:271:10)
    at Function.handle (C:\Projects\pentiadk\node_modules\express\lib\router\index.js:176:3)
    at EventEmitter.handle (C:\Projects\pentiadk\node_modules\express\lib\application.js:173:10)
    at Server.app (C:\Projects\pentiadk\node_modules\express\lib\express.js:38:9)
    at emitTwo (events.js:106:13)
    at Server.emit (events.js:191:7)
    at HTTPParser.parserOnIncoming [as onIncoming] (_http_server.js:543:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:105:23)
```

**Comment by rwjblue** [comment]
Please update to the latest version of ember-cli-fastboot, this error with 2.10 was fixed.

**Comment by bjerh** [comment]
Whoosh, so sorry about that. I'm a bit embarassed. :-|
