### ISSUE TITLE
TypeError: res.sendStatus is not a function

### ISSUE THREAD

**Issue by vvscode** [ember-fastboot/ember-cli-fastboot#357]
```TypeError: res.sendStatus is not a function
    at app.use (/Users/vvs/repo/vvroom/node_modules/ember-cli-fastboot/lib/tasks/fastboot-server.js:44:35)
    at Layer.handle [as handle_request] (/Users/vvs/repo/vvroom/node_modules/express/lib/router/layer.js:76:5)
    at trim_prefix (/Users/vvs/repo/vvroom/node_modules/express/lib/router/index.js:263:13)
    at /Users/vvs/repo/vvroom/node_modules/express/lib/router/index.js:230:9
    at Function.proto.process_params (/Users/vvs/repo/vvroom/node_modules/express/lib/router/index.js:305:12)
    at /Users/vvs/repo/vvroom/node_modules/express/lib/router/index.js:221:12
    at Function.match_layer (/Users/vvs/repo/vvroom/node_modules/express/lib/router/index.js:288:3)
    at next (/Users/vvs/repo/vvroom/node_modules/express/lib/router/index.js:182:10)
    at next (/Users/vvs/repo/vvroom/node_modules/express/lib/router/route.js:90:14)
    at failure (/Users/vvs/repo/vvroom/node_modules/fastboot-express-middleware/src/index.js:62:9)
```

the error on transition to `error` route in application

My `package.json` is
```{
  "name": "vvroom",
  "version": "5.50.0",
  "private": true,
  "description": "",
  "repository": "https://github.com/collectrium/vvroom",
  "author": "",
  "license": "",
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "npm run lint && ember test --reporter=dot",
    "reinstall-dependencies": "rm -rf node_modules/; rm -rf bower_components/; npm cache clean; bower cache clean; npm install; bower install",
    "reinstall-global": "rm -rf node_modules/apollo-global; npm cache clean; npm install",
    "lint": "eslint .",
    "lint-strict": "eslint --config .commit.eslintrc.js .",
    "buildTag": "bash -c 'git tag $(echo $(git rev-parse --abbrev-ref HEAD; )__$(date +%Y-%m-%d___%H-%M-%S)); git push --no-verify; git push --tags --no-verify;'",
    "testFastBoot": "node tests/fastboot-test-runner.js"
  },
  "devDependencies": {
    "broccoli-asset-rev": "2.2.0",
    "broccoli-merge-trees": "0.1.4",
    "broccoli-static-compiler": "0.1.4",
    "chai": "3.5.0",
    "cheerio": "0.22.0",
    "ember-cli-accounting": "0.0.4",
    "ember-cli-app-version": "1.0.0",
    "ember-cli-babel": "5.1.6",
    "ember-cli-chai": "0.3.2",
    "ember-cli-dependency-checker": "1.1.0",
    "ember-cli-deploy": "0.6.3",
    "ember-cli-deploy-build": "0.1.1",
    "ember-cli-deploy-cloudfront": "0.2.8",
    "ember-cli-deploy-display-revisions": "0.2.2",
    "ember-cli-deploy-fastboot-lambda": "https://github.com/vvscode/ember-cli-deploy-fastboot-lambda#update-fastboot",
    "ember-cli-deploy-gzip": "0.2.3",
    "ember-cli-deploy-revision-data": "0.2.3",
    "ember-cli-deploy-s3": "0.3.1",
    "ember-cli-deprecation-workflow": "0.2.3",
    "ember-cli-fastboot": "1.0.0-beta.15",
    "ember-cli-font-awesome": "1.1.1",
    "ember-cli-htmlbars-inline-precompile": "0.3.6",
    "ember-cli-ic-ajax": "0.2.4",
    "ember-cli-inject-live-reload": "1.3.0",
    "ember-cli-inspectlet": "1.0.0",
    "ember-cli-less": "1.5.3",
    "ember-cli-qunit": "3.1.1",
    "ember-cli-release": "0.2.8",
    "ember-cli-uploader": "0.3.11",
    "ember-collection": "https://github.com/emberjs/ember-collection#master",
    "ember-data": "2.10.0",
    "ember-disable-proxy-controllers": "1.0.0",
    "ember-export-application-global": "1.1.1",
    "ember-feature-flags": "2.0.0",
    "ember-i18n": "4.2.0",
    "ember-inflector": "1.9.6",
    "ember-legacy-controllers": "0.1.0",
    "ember-legacy-views": "0.2.0",
    "ember-lodash": "0.0.11",
    "ember-network": "0.3.1",
    "ember-resize-mixin": "0.1.1",
    "ember-truth-helpers": "1.2.0",
    "express": "4.8.5",
    "liquid-fire": "0.24.1",
    "mocha": "3.2.0",
    "request": "2.79.0",
    "rsvp": "3.3.3"
  },
  "dependencies": {
    "ember-cli": "2.4.3",
    "ember-cli-deploy-revision-data": "0.3.2",
    "ember-cli-htmlbars": "0.7.9",
    "ember-cli-uglify": "1.2.0",
    "ember-load-initializers": "0.5.1",
    "eslint": "^3.13.1",
    "fastboot": "1.0.0-rc.5",
    "loader.js": "4.0.2",
    "lodash": "4.16.6",
    "lodash-es": "4.17.4"
  },
  "fastbootDependencies": [
    "util"
  ]
}
```

Looks like 
```
        app.use((req, res) =>res.sendStatus(404));
```
got non-express response but NodeResponse

**Comment by kratiahuja** [comment]
Could you try this with the rc builds?

**Comment by kratiahuja** [comment]
Closing this as this is not seen in 1.x. @vvscode please feel free to reopen if this is still an issue.
