### ISSUE TITLE
TypeError: tagName.toUpperCase is not a function

### ISSUE THREAD

**Issue by Zorig** [ember-fastboot/ember-cli-fastboot#365]
Hi, i am trying to do fastboot(1.0.0-beta.15) to my ember-app(2.12). When i run `ember fastboot --serve-assets` it gives me an error
```bash
There was an error running your app in fastboot. More info about the error:
 TypeError: tagName.toUpperCase is not a function
    at new Element (/home/user/ember-app/node_modules/simple-dom/lib/simple-dom/document/element.js:4:21)
    at Document.createElement (/home/user/ember-app/node_modules/simple-dom/lib/simple-dom/document.js:23:10)
    at NodeDOMTreeConstruction.createElement (/home/user/ember-app/dist/fastboot/vendor.js:55366:34)
    at ElementStack.openElement (/home/user/ember-app/dist/fastboot/vendor.js:56432:36)
    at OpenDynamicPrimitiveElementOpcode.evaluate (/home/user/ember-app/dist/fastboot/vendor.js:59220:24)
    at VM.execute (/home/user/ember-app/dist/fastboot/vendor.js:64946:28)
    at VM.resume (/home/user/ember-app/dist/fastboot/vendor.js:64925:25)
    at TryOpcode.handleException (/home/user/ember-app/dist/fastboot/vendor.js:65436:29)
    at UpdatingVMFrame.handleException (/home/user/ember-app/dist/fastboot/vendor.js:65616:35)
    at UpdatingVM._throw [as throw] (/home/user/ember-app/dist/fastboot/vendor.js:65329:37)
```
it seems simple-dom gets some what wrong typed tagname from glimmer. Can anyone faced this? any help would be appreciated thanks.

**Comment by rwjblue** [comment]
The tag name comes from your components in general. My guess is that you have something like `tagName: somethingNotAStringHere` (could be a computed property, could be `null`, anything really other than a string may cause this error).

**Comment by tomdale** [comment]
Closing this issue because it seems likely to be a incorrectly set `tagName`. @Zorig, please comment if you are still having trouble!
