### ISSUE TITLE
Ember-Data requests that get redirected fail in FastBoot

### ISSUE THREAD

**Issue by villander** [ember-fastboot/ember-cli-fastboot#377]
When i put ember-cli-fastboot in my app, i have this error when `this.query('modelName', {})` is called. Without fastboot all works normally

I'm using

ember-cli: 2.12
ember-data: 2.12
ember: 2.12

```
Error: Ember Data Request GET https://pokeapi.co/api/v2/pokemon returned a 301
Payload (Empty Content-Type)
SyntaxError: Unexpected end of JSON input
    at EmberError.AdapterError (/Users/flama/Projects/pokemon-challenge/tmp/broccoli_merge_trees-output_path-fkHQpsYu.tmp/fastboot/vendor.js:86491:16)
    at Class.handleResponse (/Users/flama/Projects/pokemon-challenge/tmp/broccoli_merge_trees-output_path-fkHQpsYu.tmp/fastboot/vendor.js:88106:14)
    at ajaxError (/Users/flama/Projects/pokemon-challenge/tmp/broccoli_merge_trees-output_path-fkHQpsYu.tmp/fastboot/vendor.js:88604:25)
    at Object.hash.error (/Users/flama/Projects/pokemon-challenge/tmp/broccoli_merge_trees-output_path-fkHQpsYu.tmp/fastboot/vendor.js:88178:23)
    at fire (/Users/flama/Projects/pokemon-challenge/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.fireWith (/Users/flama/Projects/pokemon-challenge/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.fire [as reject] (/Users/flama/Projects/pokemon-challenge/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at onError (/Users/flama/Projects/pokemon-challenge/node_modules/najax/lib/najax.js:208:9)
    at dataHandler (/Users/flama/Projects/pokemon-challenge/node_modules/najax/lib/najax.js:153:18)
    at IncomingMessage.<anonymous> (/Users/flama/Projects/pokemon-challenge/node_modules/najax/lib/najax.js:198:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by stefanpenner** [comment]
likely a configuration issue with njax?

**Comment by kratiahuja** [comment]
Closing this as there is no activity. @villander please feel free to reopen if this is till an issue for you.
