### ISSUE TITLE
Missing "fastboot" dependency

### ISSUE THREAD

**Issue by Turbo87** [ember-fastboot/ember-cli-fastboot#382]
```
Cannot find module 'fastboot'
Error: Cannot find module 'fastboot'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/travis/build/simplabs/ember-cookies/node_modules/ember-cli-fastboot/index.js:10:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

it looks like we are using the `fastboot` package [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/c03aa4c24ba6dacc1dda8aca72d21d8ccfcce94c/index.js#L10) but it is not declared as a dependency in the [`package.json`](https://github.com/ember-fastboot/ember-cli-fastboot/blob/c03aa4c24ba6dacc1dda8aca72d21d8ccfcce94c/package.json#L21-L42) file

**Comment by simonihmig** [comment]
I remember having seen this in Travis builds using npm@2, but forgot to investigate this further. With npm@3 it works, probably because `fastboot` comes as a transitive dependency, and npm@3 flattens the dependencies, so a `require` would still work. But iirc npm@2 will install this as a local dependency, not at the root of `node_modules`, so this fails. The PR #383 should fix this.

**Comment by kratiahuja** [comment]
It works in Travis because we upgraded to npm@3 with this [PR](https://github.com/ember-fastboot/ember-cli-fastboot/pull/350)

**Comment by simonihmig** [comment]
@kratiahuja I think they are, as the node 4 setup if Travis ships with npm@2 by default: https://travis-ci.org/simplabs/ember-cookies/jobs/224675470#L315

**Comment by Turbo87** [comment]
FWIW ember-cli 2.12+ needs npm 3+ anyway, so it's not that relevant, but still seems like the right thing to do
