### ISSUE TITLE
Ember Fastboot RC1

### ISSUE THREAD

**Issue by devotox** [ember-fastboot/ember-cli-fastboot#400]
Ember CLI 2.13.2
Ember 2.13.1
Node 6.10.3

```
App is being served by FastBoot
ReferenceError: define is not defined
    at /Users/devonte/Documents/Doctify/platform/intranet-beta/tmp/broccoli_merge_trees-output_path-HbmHtbrw.tmp/assets/doctify/adapters/application.js:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at Sandbox.VMSandbox.eval (/Users/devonte/Documents/Doctify/platform/intranet-beta/node_modules/fastboot/src/vm-sandbox.js:14:14)
    at /Users/devonte/Documents/Doctify/platform/intranet-beta/node_modules/fastboot/src/ember-app.js:149:15
```

Also

```
ReferenceError: define is not defined
    at /Users/devonte/Documents/Doctify/platform/intranet-beta/tmp/broccoli_merge_trees-output_path-Jhz7F6lD.tmp/assets/doctify/account/tests/addon.lint-test.js:1:1
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at Sandbox.VMSandbox.eval (/Users/devonte/Documents/Doctify/platform/intranet-beta/node_modules/fastboot/src/vm-sandbox.js:14:14)
    at /Users/devonte/Documents/Doctify/platform/intranet-beta/node_modules/fastboot/src/ember-app.js:149:15
```

```javascript
import Ember from 'ember';

import DS from 'ember-data';

const { RESTAdapter } = DS;

export default RESTAdapter.extend( {
});
```

**Comment by kratiahuja** [comment]
Spoke over slack, your app wasn't containing any `vendorFiles` to load therefore the loader wasn't loaded in the sandbox.

closing this.
