### ISSUE TITLE
Serve breaks, unhelpful error messages in rc.1

### ISSUE THREAD

**Issue by vlascik** [ember-fastboot/ember-cli-fastboot#425]
I'm trying rc.1, but my app breaks, error message is completely unhelpful and breakpoints in `registerInstanceInitializers` do not work, regardless if I set it in dist/assets/vendor.js or that broccoli output directory. What could be wrong, how do I debug this?
```
Error
    at assert (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\vendor\ember\ember.debug.js:13688:1)
    at Function.registry.optionsForType.singleton [as instanceInitializer] (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\vendor\ember\ember.debug.js:12476:1)
    at registerInstanceInitializers (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\addon-tree-output\ember-load-initializers\index.js:48:1)
    at exports.default (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\addon-tree-output\ember-load-initializers\index.js:25:1)
    at Module.callback (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\project\app.js:101:1)
    at Module.exports (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\vendor\loader\loader.js:105:1)
    at Module._reify (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\vendor\loader\loader.js:140:1)
    at Module.reify (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\vendor\loader\loader.js:127:1)
    at Module.exports (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\vendor\loader\loader.js:103:1)
    at Object.requireModule (P:\Project\tmp\broccoli_merge_trees-output_path-npoJye1k.tmp\assets\vendor\loader\loader.js:29:1)
    at VMSandbox.run (P:\Project\node_modules\fastboot\src\vm-sandbox.js:18:13)
    at EmberApp.createEmberApp (P:\Project\node_modules\fastboot\src\ember-app.js:164:30)
    at new EmberApp (P:\Project\node_modules\fastboot\src\ember-app.js:50:21)
    at FastBoot._buildEmberApp (P:\Project\node_modules\fastboot\src\index.js:114:17)
    at new FastBoot (P:\Project\node_modules\fastboot\src\index.js:52:10)
    at app.use (P:\Project\node_modules\ember-cli-fastboot\index.js:233:29)
    at Layer.handle [as handle_request] (P:\Project\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (P:\Project\node_modules\express\lib\router\index.js:317:13)
    at P:\Project\node_modules\express\lib\router\index.js:284:7
    at next (P:\Project\node_modules\express\lib\router\index.js:275:10)
    at err (P:\Project\node_modules\ember-cli\lib\tasks\server\middleware\broccoli-watcher\index.js:54:11)
    at watcher.then.errorHandler.buildError (P:\Project\node_modules\broccoli-middleware\lib\watcher-middleware.js:35:7)
    at tryCatch (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:216:12)
    at invokeCallback (P:\Project\node_modules\rsvp\dist\lib\rsvp\-internal.js:231:13)
    at flush (P:\Project\node_modules\rsvp\dist\lib\rsvp\asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

**Comment by kratiahuja** [comment]
A minimal reproduction of the app is required in order to help further. what versions of ember, Ember-cli are you using ?

**Comment by vlascik** [comment]
Latest 2.14 betas.
Where should I put breakpoints, inside vendor.js or elsewhere?
I will try to come up with a reproduction, but that might be tricky, it's a large app.

**Comment by kratiahuja** [comment]
Have you made sure all  fastboot complaint addons that you are usingare compatible with the new fastboot semantics?

**Comment by vlascik** [comment]
That's quite impossible at the moment, there are just too many, I did what I could by wrapping libraries that I know are breaking fastboot by using this: https://github.com/ember-cli/ember-cli/pull/7117 and wanted to go on fixing the rest, before hitting the brick wall because of the unhelpful error message and breakpoints that don't seem to work.

**Comment by kratiahuja** [comment]
@vlascik Have you seen #387 ? which is already fixing some of the addons. The `ember-cli` PR you listed is nice to have but there are other ways to fix the same problem. See the migration guide listed in #387.

Just by looking at the stack trace, it doesn't look like the error is coming from the app. A minimal reproduction or what all versions you are using is needed in order reproduce and help further. My gut tells me is to check if you have some browser or fastboot initializers. Your app boot is failing itself to load the initializers.

**Comment by kratiahuja** [comment]
Also can you check what happens when you run hit your app with `fastboot=false` query param? does the app load?

**Comment by vlascik** [comment]
I updated all addons that have PRs already, that didn't help, but I will double-check if something wasn't fixed in the meantime.
Imho something like that transformation would be pretty helpful (I see that you did other similar PR for that) to avoid adding loads of boilerplate to ember-cli-build.js and addons. The details of this transformation should be hidden as much as possible, otherwise if you let your users do it, if you'll need to change something in any point in the future, you will have another list of ~200 addons to fix, and that's just not a good way to go about it.
With fastboot=false the app works, it was the first thing I checked.
What bothers me is how unhelpful the error message is, can something be done about that? E.g. adding some information on which initializer fails.
Also, does putting the breakpoints to vendor.js work for you?

**Comment by kratiahuja** [comment]
The details will be hidden with something via [fastboot-transform](https://github.com/kratiahuja/fastboot-transform), however addons that want to make themselves compatible with `fastboot` will need to use it. 

> What bothers me is how unhelpful the error message is, can something be done about that?

Ofcourse. If you would like to PR something from your debugging, happy to review it.

> Also, does putting the breakpoints to vendor.js work for you?

Where are you putting the breakpoints? Are you using this: https://github.com/ember-fastboot/ember-cli-fastboot#troubleshooting ?

If you can give me a list of addons your app is depening upon, I can help create a reproduction.

**Comment by vlascik** [comment]
Thanks for the assistance, I was able to fix it after all (console.logging to find faulty initializers). Turns out the first version of `ember-cli-head` PR for fastboot compatibility was broken and they did another one 3 days ago.
After updating that and ember-fetch the app boots.
There seems to be one more problem with it, which I reported there.
Thanks again, I'll close this.
