### ISSUE TITLE
Error with ember fastboot in production

### ISSUE THREAD

**Issue by mrispoli24** [ember-fastboot/ember-cli-fastboot#429]
I am having issues with ember fastboot in production.

I tried deploying to heroku which is when I first noted the error:

Should I be adding a vendor.js file somewhere?

```
Error: ENOENT: no such file or directory, open '/Users/M/code/cause_of_a_kind/tmp/srihash_assets-output_path-3x4mmjGu.tmp/assets/vendor.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at /Users/M/code/cause_of_a_kind/node_modules/fastboot/src/ember-app.js:141:27
    at Array.forEach (native)
    at EmberApp.loadAppFiles (/Users/M/code/cause_of_a_kind/node_modules/fastboot/src/ember-app.js:139:21)
    at EmberApp.retrieveSandboxedApp (/Users/M/code/cause_of_a_kind/node_modules/fastboot/src/ember-app.js:187:10)
    at new EmberApp (/Users/M/code/cause_of_a_kind/node_modules/fastboot/src/ember-app.js:50:21)
    at FastBoot._buildEmberApp (/Users/M/code/cause_of_a_kind/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/M/code/cause_of_a_kind/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/M/code/cause_of_a_kind/node_modules/ember-cli-fastboot/index.js:233:29)
```

**Comment by kratiahuja** [comment]
Are your assets fingerprinted?

**Comment by mrispoli24** [comment]
@kratiahuja oh man this seems to have fixed it! Thank you so much.  

For anyone that comes across this just had to add the below to ember-cli-build.js

```js
var app = new EmberApp(defaults, {
    fingerprint: {
      enabled: true,
      generateAssetMap: true
    }
  });
```

**Comment by kratiahuja** [comment]
@mrispoli24 we tracking this issue in #424 as well.
