### ISSUE TITLE
Error when attempting to serve addon's dummy app in prod mode without fingerprinting.

### ISSUE THREAD

**Issue by kybishop** [ember-fastboot/ember-cli-fastboot#439]
To reproduce:

1. Checkout [ember-popper](https://github.com/kybishop/ember-popper)
2. `yarn install`
3. Remove [fingerprint hash](https://github.com/kybishop/ember-popper/blob/master/ember-cli-build.js#L9) from options
4. `ember s --prod`

Result:

```
App is being served by FastBoot
Error: ENOENT: no such file or directory, open '/Users/kybishop/github/ember/ember-popper/tmp/srihash_assets-output_path-5x2CnPFh.tmp/assets/vendor.js'
    at Object.fs.openSync (fs.js:557:18)
    at Object.fs.readFileSync (fs.js:467:33)
    at /Users/kybishop/github/ember/ember-popper/node_modules/fastboot/src/ember-app.js:141:27
    at Array.forEach (native)
    at EmberApp.loadAppFiles (/Users/kybishop/github/ember/ember-popper/node_modules/fastboot/src/ember-app.js:139:21)
    at EmberApp.retrieveSandboxedApp (/Users/kybishop/github/ember/ember-popper/node_modules/fastboot/src/ember-app.js:187:10)
    at new EmberApp (/Users/kybishop/github/ember/ember-popper/node_modules/fastboot/src/ember-app.js:50:21)
    at FastBoot._buildEmberApp (/Users/kybishop/github/ember/ember-popper/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/kybishop/github/ember/ember-popper/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/kybishop/github/ember/ember-popper/node_modules/ember-cli-fastboot/index.js:239:29)
```

A more descriptive error would be super helpful if this bug cannot be avoided.

**Comment by kratiahuja** [comment]
@kybishop I looked at your addon and for some reason `yarn install` was downloading rc3 which doesn't have the fingerprinting fix. Reinstalling ember-cli-fastboot downloaded rc.5 which has the fix and it worked as expected. 

The more descriptive error was fixed after rc.3, so I am going to close this issue. Please update your yarn.lock to fetch rc.5

**Comment by kybishop** [comment]
@kratiahuja looks like ember-cli-fastboot was mistakenly published to 1.0.0-rc3 in the past (vs 1.0.0-rc.3). This causes yarn to consider 1.0.0-rc3 a higher version number than 1.0.0-rc.5, so apps doing anything like `"ember-cli-fastboot": "^1.0.0-rc.1"` (including my own) will resolve to rc3 until fastboot's release.

**Comment by kybishop** [comment]
@kratiahuja Regardless of the aforementioned bork, thank you for looking into the issue!

**Comment by kratiahuja** [comment]
yup that was a typo in the release version on my part.

**Comment by tomdale** [comment]
@kratiahuja Can we yank 1.0.0-rc.3?

**Comment by kratiahuja** [comment]
@tomdale sure I can do that

**Comment by kratiahuja** [comment]
We couldn't unpublish the version so we decided to publish `1.0.0-rc6` with `1.0.0-rc.6`. We'll need to maintain two parallel rcs for a while but that's fine than causing more issues for folks using rc3.
