### ISSUE TITLE
userAgent Issue swiper.js

### ISSUE THREAD

**Issue by ivanhueso** [ember-fastboot/ember-cli-fastboot#455]
I've the following error when I try to use [Swiper.js](http://idangero.us/swiper/#.WXgnndPytbU) with Fastboot '^1.0.0' 

     TypeError: Cannot read property 'userAgent' of undefined
         at /Users/ivanhueso/Documents/Panda/panda-bao-bao/tmp/broccoli_merge_trees-output_path-49NwK1AR.tmp/assets/swiper.js:4497:29
         at /Users/ivanhueso/Documents/Panda/panda-bao-bao/tmp/broccoli_merge_trees-output_path-49NwK1AR.tmp/assets/swiper.js:4498:102
         at /Users/ivanhueso/Documents/Panda/panda-bao-bao/tmp/broccoli_merge_trees-output_path-49NwK1AR.tmp/assets/swiper.js:5337:21
         at ContextifyScript.Script.runInContext (vm.js:35:29)
         at VMSandbox.eval (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/vm-sandbox.js:14:16)
         at /Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/ember-app.js:136:15
         at Array.forEach (native)
         at EmberApp.loadAppFiles (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/ember-app.js:133:21)
         at EmberApp.retrieveSandboxedApp (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/ember-app.js:181:10)
         at new EmberApp (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/ember-app.js:49:21)
         at FastBoot._buildEmberApp (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/index.js:114:17)
         at new FastBoot (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/fastboot/src/index.js:52:10)
         at app.use (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli-fastboot/index.js:247:29)
         at Layer.handle [as handle_request] (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/layer.js:95:5)
         at trim_prefix (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/index.js:317:13)
         at /Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/index.js:284:7
         at Function.process_params (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/express/lib/router/index.js:335:12)
         at next (/Users/ivanhueso/Documents/Panda/panda-bao bao/node_modules/express/lib/router/index.js:275:10)
         at err (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
         at watcher.then (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
         at tryCatch (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:12)
         at invokeCallback (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:13)
         at /Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
         at flush (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
         at _combinedTickCallback (internal/process/next_tick.js:73:7)
         at process._tickCallback (internal/process/next_tick.js:104:9)

Any idea how can I solve this issue within Fastboot without modifying the Swiper.js file itself.

Reference:
[http://suven.github.io/ember-cli-swiper/](http://suven.github.io/ember-cli-swiper/)

**Comment by mschinis** [comment]
@ivanhueso there is currently an open issue on ember-cli-swiper for supporting fastboot 1.0. 
https://github.com/Suven/ember-cli-swiper/issues/59

**Comment by kratiahuja** [comment]
Going to close this since this is a ember-cli-swiper issue and not fastboot.
