### ISSUE TITLE
Cannot read property 'fastboot' of undefined

### ISSUE THREAD

**Issue by Peter-Barrett** [ember-fastboot/ember-cli-fastboot#456]
Hey,

I'm getting this on `ember serve`, any idea what's going on?

ember-cli: 2.15.0-beta.1
ember-data: 2.14.7
ember-cli-fastboot: 1.0.1

```Cannot read property 'fastboot' of undefined
TypeError: Cannot read property 'fastboot' of undefined
    at postBuild (/Users/p/project/node_modules/ember-cli-fastboot/index.js:266:13)
    at addonPromises.project.addons.reduce (/Users/p/project/node_modules/ember-cli/lib/models/builder.js:138:21)
    at Array.reduce (native)
    at Builder.processAddonBuildSteps (//Users/p/project/node_modules/ember-cli/lib/models/builder.js:135:43)
    at tryCatch (/Users/p/project/node_modules/rsvp/dist/rsvp.js:538:12)
    at invokeCallback (/Users/p/project/node_modules/rsvp/dist/rsvp.js:553:13)
    at publish (/Users/p/project/node_modules/rsvp/dist/rsvp.js:521:7)
    at flush (/Users/p/project/node_modules/rsvp/dist/rsvp.js:2373:5)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)```

**Comment by kratiahuja** [comment]
There is a bug in ember-cli 2.15.0-beta.1 which has been fixed in master but a new beta hasn't been released. I suggest use Ember CLI 2.14 for now.

**Comment by kratiahuja** [comment]
@Peter-Barrett I am going to close this since this is a bug in Ember CLI beta release. Please feel free to reopen if this is still an issue in Ember CLI 2.14
