### ISSUE TITLE
Introducing fastboot to existing Ember app - TypeError: Cannot read property 'documentMode' of undefined

### ISSUE THREAD

**Issue by serv** [ember-fastboot/ember-cli-fastboot#461]
I have an Ember app that currently isn't using any serverside component.

Ember | 2.12.2
Ember Data | 2.13.2
jQuery | 3.2.1

I want to introduce a very simple serverside part to this app that basically renders the index page and nothing else.

I followed the instructions here and ran the following

```
ember install ember-fetch
ember install ember-cli-fastboot
```

When I go to the homepage I get this error message,

```
$ npm start

> webclient-cli@3.23.16 start /Users/jasonkim/work/node/webclient-cli
> ember server

Could not start watchman
Visit https://ember-cli.com/user-guide/#watchman for more info.
WARNING: Empty `rootURL` is not supported. Disable history support, or use an absolute `rootURL`
Livereload server on http://localhost:49153
Serving on http://localhost:8080/
DEPRECATION: ember-addon.fastBootDependencies has been replaced with ember-addon.fastbootDependencies [addon: ember-cli-moment-shim]

Build successful - 13907ms.

Slowest Nodes (totalTime => 5% )              | Total (avg)
----------------------------------------------+---------------------
Babel (23)                                    | 5379ms (233 ms)
Concat (9)                                    | 3775ms (419 ms)
TemplateCompiler (3)                          | 1335ms (445 ms)
SassCompiler (1)                              | 1115ms

App is being served by FastBoot
TypeError: Cannot read property 'documentMode' of undefined
    at /Users/jasonkim/work/node/webclient-cli/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-tqbJOKBM.tmp/assets/vendor/velocity/velocity.js:461:1
    at /Users/jasonkim/work/node/webclient-cli/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-tqbJOKBM.tmp/assets/vendor/velocity/velocity.js:478:1
    at /Users/jasonkim/work/node/webclient-cli/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-tqbJOKBM.tmp/assets/vendor/velocity/velocity.js:4760:1
    at i (/Users/jasonkim/work/node/webclient-cli/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-tqbJOKBM.tmp/assets/vendor/velocity/velocity.js:428:1)
    at /Users/jasonkim/work/node/webclient-cli/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-tqbJOKBM.tmp/assets/vendor/velocity/velocity.js:436:1
    at /Users/jasonkim/work/node/webclient-cli/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-tqbJOKBM.tmp/assets/vendor.js:83600:3
    at ContextifyScript.Script.runInContext (vm.js:35:29)
    at VMSandbox.eval (/Users/jasonkim/work/node/webclient-cli/node_modules/fastboot/src/vm-sandbox.js:14:16)
    at /Users/jasonkim/work/node/webclient-cli/node_modules/fastboot/src/ember-app.js:136:15
    at Array.forEach (native)
    at EmberApp.loadAppFiles (/Users/jasonkim/work/node/webclient-cli/node_modules/fastboot/src/ember-app.js:133:21)
    at EmberApp.retrieveSandboxedApp (/Users/jasonkim/work/node/webclient-cli/node_modules/fastboot/src/ember-app.js:181:10)
    at new EmberApp (/Users/jasonkim/work/node/webclient-cli/node_modules/fastboot/src/ember-app.js:49:21)
    at FastBoot._buildEmberApp (/Users/jasonkim/work/node/webclient-cli/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/Users/jasonkim/work/node/webclient-cli/node_modules/fastboot/src/index.js:52:10)
    at app.use (/Users/jasonkim/work/node/webclient-cli/node_modules/ember-cli-fastboot/index.js:247:29)
    at Layer.handle [as handle_request] (/Users/jasonkim/work/node/webclient-cli/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/jasonkim/work/node/webclient-cli/node_modules/express/lib/router/index.js:317:13)
    at /Users/jasonkim/work/node/webclient-cli/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/jasonkim/work/node/webclient-cli/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/jasonkim/work/node/webclient-cli/node_modules/express/lib/router/index.js:275:10)
    at err (/Users/jasonkim/work/node/webclient-cli/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Users/jasonkim/work/node/webclient-cli/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatch (/Users/jasonkim/work/node/webclient-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:198:12)
    at invokeCallback (/Users/jasonkim/work/node/webclient-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:13)
    at /Users/jasonkim/work/node/webclient-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Users/jasonkim/work/node/webclient-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Does anyone know how to fix `TypeError: Cannot read property 'documentMode' of undefined` problem?

**Comment by kratiahuja** [comment]
I believe this is because of velocity.js which comes in via liquid fire. You might want to upgrade to the latest liquid-fire version. Since this is a question rather than a bug, I am inclined to close this. Please feel free to reach out on the #-fastboot channel on ember community.
