### ISSUE TITLE
The Broccoli Plugin: [BroccoliMergeTrees] failed with

### ISSUE THREAD

**Issue by ivanhueso** [ember-fastboot/ember-cli-fastboot#464]
Hi I got this error when trying to build `ember b -p`

     The Broccoli Plugin: [BroccoliMergeTrees] failed with:
     SyntaxError: Unexpected token: operator (<)
      at JS_Parse_Error.get (eval at <anonymous> (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
      at new BroccoliBuildError (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-builder/lib/broccoli-build-error.js:18:29)
       at /Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-builder/lib/builder.js:168:19
       at tryCatch (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:525:12)
       at invokeCallback (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:538:13)
       at publish (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:508:7)
       at publishRejection (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:443:3)
       at flush (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/rsvp/dist/rsvp.js:2415:5)
       at _combinedTickCallback (internal/process/next_tick.js:73:7)
       at process._tickCallback (internal/process/next_tick.js:104:9)

    The broccoli plugin was instantiated at:
        at BroccoliMergeTrees.Plugin (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/broccoli-plugin/index.js:7:31)
        at new BroccoliMergeTrees (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli-fastboot/node_modules/broccoli-merge-trees/index.js:16:10)
        at Class.postprocessTree (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli-fastboot/index.js:197:14)
       at projectOrAddon.addons.reduce (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/utilities/addon-process-tree.js:6:25)
       at Array.reduce (native)
       at addonProcessTree (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/utilities/addon-process-tree.js:4:32)
       at EmberApp.addonPostprocessTree (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/broccoli/ember-app.js:596:12)
       at EmberApp.toTree (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/broccoli/ember-app.js:1699:17)
       at module.exports (/Users/ivanhueso/Documents/Panda/panda-bao-bao/ember-cli-build.js:35:16)
       at Builder.setupBroccoliBuilder (/Users/ivanhueso/Documents/Panda/panda-bao-bao/node_modules/ember-cli/lib/models/builder.js:56:19)

**Comment by kratiahuja** [comment]
Can you please provide a minimal reproduction? Seems like you have an build error
