### ISSUE TITLE
"fastbootMiddleware is not a function"

### ISSUE THREAD

**Issue by marcoow** [ember-fastboot/ember-cli-fastboot#478]
We're seeing this error from time to time when switching branches while leaving `ember s` running. I haven't digged deeper into it but though I'd open this as a heads up already.

Stacktrace:

```
TypeError: fastbootMiddleware is not a function
    at app.use (/Users/<Redacted>/Projets/mweb/node_modules/ember-cli-fastboot/index.js:256:11)
    at Layer.handle [as handle_request] (/Users/<Redacted>/Projets/mweb/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/<Redacted>/Projets/mweb/node_modules/express/lib/router/index.js:312:13)
    at /Users/<Redacted>/Projets/mweb/node_modules/express/lib/router/index.js:280:7
    at Function.process_params (/Users/<Redacted>/Projets/mweb/node_modules/express/lib/router/index.js:330:12)
    at next (/Users/<Redacted>/Projets/mweb/node_modules/express/lib/router/index.js:271:10)
    at err (/Users/<Redacted>/Projets/mweb/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Users/<Redacted>/Projets/mweb/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatch (/Users/<Redacted>/Projets/mweb/node_modules/rsvp/dist/lib/rsvp/-internal.js:215:12)
    at invokeCallback (/Users/<Redacted>/Projets/mweb/node_modules/rsvp/dist/lib/rsvp/-internal.js:230:13)
    at /Users/<Redacted>/Projets/mweb/node_modules/rsvp/dist/lib/rsvp/then.js:29:16
    at flush (/Users/<Redacted>/Projets/mweb/node_modules/rsvp/dist/lib/rsvp/asap.js:85:5)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Update**

By looking at the code it's pretty clear when this would happen (`this.fastboot` being `false` [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L243) resulting in `undefined(req, resp, next)` [here](https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L256)), I'm just not sure what the scenario is in which that could be the case.

I'm not sure if something like this would make sense?

```js
if (!this.fastboot || !this.fastbootMiddleware) {
  // TODO(future): make this configurable for allowing apps to pass sandboxGlobals
  // and custom sandbox class
  this.ui.writeLine(chalk.green('App is being served by FastBoot'));
  this.fastboot = new FastBoot({
    distPath: outputPath
  });

  this.fastbootMiddleware = FastBootExpressMiddleware({
    fastboot: this.fastboot
  });
}

this.fastbootMiddleware(req, resp, next);
```

**Comment by kratiahuja** [comment]
How is `this.fastboot` false? That doesn't sound like the right value. 

Can you try without this change: https://github.com/ember-fastboot/ember-cli-fastboot/pull/427/files and see if it fixes for you. (I remember trying this workflow when I had introduced the unification).

**Comment by marcoow** [comment]
We're having trouble reproducing this but it seems like that change might be the reason for the problem actually. I'll have another look tomorrow.

**Comment by kratiahuja** [comment]
Thanks @marcoow! Let me know if that fixes it for you, I'll revert that.

**Comment by marcoow** [comment]
I was able to reproduce the error. I added some logging to https://github.com/ember-fastboot/ember-cli-fastboot/blob/master/index.js#L243:

```js
console.log('debug', this.fastboot, fastbootMiddleware);
if (!this.fastboot) {
```

When the error occurs, `this.fastboot` is defined but `fastbootMiddleware` is undefined. Thus, reverting #427 would actually fix it.

**Comment by kratiahuja** [comment]
Cool, I'll revert and release today
