### ISSUE TITLE
TypeError: Cannot read property 'js' of undefined : Glimmerjs + Fastboot Fails

### ISSUE THREAD

**Issue by rajasoun** [ember-fastboot/ember-cli-fastboot#520]
Fastboot Fails on Glimmer App

Steps To Reproduce:
1. git clone https://github.com/rajasoun/rapid-stack/tree/master/applications/web-ui
2. yarn 
3. ember install ember-cli-fastboot
4. yarn build

Error:

The Broccoli Plugin: [BroccoliMergeTrees] failed with:
TypeError: Cannot read property 'js' of undefined
    at FastBootConfig.buildManifest (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-config.js:158:75)
    at FastBootConfig.build (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/ember-cli-fastboot/lib/broccoli/fastboot-config.js:64:10)
    at /Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/broccoli-plugin/read_compat.js:93:34
    at tryCatch (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/rsvp/dist/rsvp.js:525:12)
    at invokeCallback (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/rsvp/dist/rsvp.js:538:13)
    at publish (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/rsvp/dist/rsvp.js:508:7)
    at flush (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/rsvp/dist/rsvp.js:2415:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

The broccoli plugin was instantiated at:
    at BroccoliMergeTrees.Plugin (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/ember-cli-fastboot/node_modules/broccoli-merge-trees/index.js:16:10)
    at Class.postprocessTree (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/ember-cli-fastboot/index.js:199:14)
    at /Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/ember-build-utilities/dist/lib/addons/process-tree.js:10:25
    at Array.reduce (<anonymous>)
    at addonProcessTree (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/ember-build-utilities/dist/lib/addons/process-tree.js:8:32)
    at GlimmerApp.package (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:261:19)
    at GlimmerApp.toTree (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/@glimmer/application-pipeline/dist/lib/broccoli/glimmer-app.js:287:28)
    at module.exports (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/ember-cli-build.js:73:12)
    at Builder.setupBroccoliBuilder (/Users/rajasoun/Workspace/ck/critical/rapid-stack/applications/web-ui/node_modules/ember-cli/lib/models/builder.js:56:19)

**Comment by rajasoun** [comment]
Is there any update on this Issue

**Comment by kratiahuja** [comment]
I don't think fastboot supports glimmer app yet.

**Comment by rajasoun** [comment]
Thanks @kratiahuja . 

Fastboot Team - Can you confirm Pls.

**Comment by danmcclain** [comment]
@rajasoun Krati is on the FastBoot team and is correct 😄

**Comment by rajasoun** [comment]
Thanks. Is Glimmer ready for Time?

**Comment by kellyselden** [comment]
@rajasoun This is the wrong team to answer that question, but I believe the answer to be probably not.

Regarding the issue. It's not really a bug, it's more like it's a future feature that no one has put the work in to add yet. Thanks for filling!
