### ISSUE TITLE
There was an error running your app in fastboot. More info about the error:

### ISSUE THREAD

**Issue by villander** [ember-fastboot/ember-cli-fastboot#558]
I hava this error when run my app with ember-cli-fastboot

```
App is being served by FastBoot
DEBUG: -------------------------------
DEBUG: Ember      : 2.17.0-beta.6
DEBUG: Ember Data : 2.17.0
DEBUG: -------------------------------
There was an error running your app in fastboot. More info about the error: 
 Error: Assertion Failed: calling set on destroyed object: <book-store-client@router:main::ember281>.targetState = <(unknown mixin):ember282>
    at EmberError.Error (native)
    at new EmberError (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/ember-debug/error.js:40:1)
    at Object.assert (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/ember-debug/index.js:139:1)
    at set (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/ember-metal.js:2922:1)
    at Class.set (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/ember-runtime/mixins/observable.js:103:1)
    at Class._handleSlowTransition (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/ember-routing/system/router.js:753:1)
    at invokeWithOnError (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:281:1)
    at Queue.flush (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:153:1)
    at DeferredActionQueues.flush (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:345:1)
    at Backburner.end (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:455:1)
    at Timeout.Backburner._boundAutorunEnd [as _onTimeout] (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:417:1)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
TypeError: Cannot read property '0' of undefined
    at Class.error (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/book-store-client/routes/application.js:13:1)
    at Class.triggerEvent (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/ember-routing/system/router.js:1027:1)
    at _trigger (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/router.js:88:1)
    at Transition.trigger (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/router.js:501:1)
    at /Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/router.js:423:1
    at tryCatcher (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/rsvp.js:215:1)
    at invokeCallback (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/rsvp.js:393:1)
    at publish (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/rsvp.js:379:1)
    at publishRejection (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/rsvp.js:314:1)
    at /Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/ember-testing/ext/rsvp.js:14:1
    at invokeWithOnError (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:283:1)
    at Queue.flush (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:153:1)
    at DeferredActionQueues.flush (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:345:1)
    at Backburner.end (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:455:1)
    at Timeout.Backburner._boundAutorunEnd [as _onTimeout] (/Users/flama/Projects/book-store-client/tmp/broccoli_persistent_filterautoprefixer_filter-output_path-NzDX1qzM.tmp/assets/backburner.js:417:1)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by villander** [comment]
@kratiahuja

**Comment by kratiahuja** [comment]
@villander a minimal reproduction will be helpful because i have no way to to see what the error is and how to reproduce it.
