### ISSUE TITLE
Error with ember fastboot on production

### ISSUE THREAD

**Issue by villander** [ember-fastboot/ember-cli-fastboot#559]
```
ember-cli: 2.17.0
node: 6.9.2
os: darwin x64
"ember-cli-fastboot": "^1.1.0",
```

I have this error, when make deploy on heroku. My app is in this repo: https://github.com/villander/vanes 

```
/app/node_modules/fastboot/src/ember-app.js:350
2017-12-09T04:30:05.770148+00:00 app[web.1]:       throw new Error(`Couldn't find ${pkgPath}. You may need to update your version of ember-cli-fastboot.`);
2017-12-09T04:30:05.770149+00:00 app[web.1]:       ^
2017-12-09T04:30:05.770150+00:00 app[web.1]: 
2017-12-09T04:30:05.770150+00:00 app[web.1]: Error: Couldn't find /app/dist/package.json. You may need to update your version of ember-cli-fastboot.
2017-12-09T04:30:05.770151+00:00 app[web.1]:     at EmberApp.readPackageJSON (/app/node_modules/fastboot/src/ember-app.js:350:13)
2017-12-09T04:30:05.770152+00:00 app[web.1]:     at new EmberApp (/app/node_modules/fastboot/src/ember-app.js:34:23)
2017-12-09T04:30:05.770153+00:00 app[web.1]:     at FastBoot._buildEmberApp (/app/node_modules/fastboot/src/index.js:114:17)
2017-12-09T04:30:05.770154+00:00 app[web.1]:     at new FastBoot (/app/node_modules/fastboot/src/index.js:52:10)
2017-12-09T04:30:05.770154+00:00 app[web.1]:     at Worker.buildMiddleware (/app/node_modules/fastboot-app-server/src/worker.js:73:21)
2017-12-09T04:30:05.770155+00:00 app[web.1]:     at Worker.start (/app/node_modules/fastboot-app-server/src/worker.js:47:30)
2017-12-09T04:30:05.770156+00:00 app[web.1]:     at new FastBootAppServer (/app/node_modules/fastboot-app-server/src/fastboot-app-server.js:51:19)
2017-12-09T04:30:05.770156+00:00 app[web.1]:     at Object.<anonymous> (/app/serve.js:3:14)
2017-12-09T04:30:05.770157+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-12-09T04:30:05.770158+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
```

**Comment by villander** [comment]
@kratiahuja
