### ISSUE TITLE
Ember CLI 3.0 compatibility

### ISSUE THREAD

**Issue by mixonic** [ember-fastboot/ember-cli-fastboot#563]
ember-cli-fastboot is not compatible with Ember CLI 3.0-beta.1. Known issues:

* [ ] In https://github.com/ember-cli/ember-cli/pull/7525 Ember CLI removed `project.nodeModulesPath`. This is used in ember-cli-fastboot for [detection of app initializers provided by addons](https://github.com/ember-fastboot/ember-cli-fastboot/blob/fb410e1f32b1b70a512de8b0a8742570eb672962/lib/build-utilities/migrate-initializers.js#L92).

**Comment by rwjblue** [comment]
Thanks for reporting!

**Comment by rondale-sc** [comment]
I ran into this one as well.

**Comment by kratiahuja** [comment]
I'll look into this next week. Apologies for the delay here. Have been on vacation.

**Comment by 0xadada** [comment]
Just tried upgrading to Ember 3.0.0.beta.1 using `ember update` command from ember-cli-update addon. After resolving conflicts, i ran `ember s` and ran into the error below.

Just ran into this problem as well, initially filed over at https://github.com/ember-cli/ember-cli/issues/7552

upgrade is on a branch here https://github.com/mirai-audio/mir/tree/16/library-ember-3beta

---

Output from `ember version --verbose && npm --version && yarn --version`:
```
$ ember version --verbose && npm --version && yarn --version
ember-cli: 3.0.0-beta.1
http_parser: 2.7.0
node: 8.9.3
v8: 6.1.534.48
uv: 1.15.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 57
nghttp2: 1.25.0
openssl: 1.0.2n
icu: 59.1
unicode: 9.0
cldr: 31.0.1
tz: 2017b
os: darwin x64
5.5.1
1.3.2
```


trace of bug
```
$ ember s
Path must be a string. Received undefined


Stack Trace and Error Report: /var/folders/ss/sjsdtptn7j1cc6y_x8lbc3ch0000gn/T/error.dump.118f766ba9e6854a07cd61a8428bd49e.log
```
then
```
$ cat /var/folders/ss/sjsdtptn7j1cc6y_x8lbc3ch0000gn/T/error.dump.118f766ba9e6854a07cd61a8428bd49e.log
=================================================================================

ENV Summary:

  TIME: Fri Jan 12 2018 16:30:30 GMT-0500 (EST)
  TITLE: ember
  ARGV:
  - /Users/ron/.nvm/versions/node/v8.9.3/bin/node
  - /usr/local/bin/ember
  - s
  EXEC_PATH: /Users/ron/.nvm/versions/node/v8.9.3/bin/node
  TMPDIR: /var/folders/ss/sjsdtptn7j1cc6y_x8lbc3ch0000gn/T
  SHELL: /usr/local/bin/bash
  PATH:
  - /Users/ron/.pyenv/shims
  - /Users/ron/.rvm/gems/ruby-head/bin
  - /Users/ron/.rvm/gems/ruby-head@global/bin
  - /Users/ron/.rvm/rubies/ruby-head/bin
  - /Users/ron/.nvm/versions/node/lts/*/bin
  - /Users/ron/.nvm/versions/node/v8.9.3/bin
  - /usr/local/bin
  - /usr/bin
  - /bin
  - /usr/sbin
  - /sbin
  - /usr/local/MacGPG2/bin
  - /Users/ron/bin
  - /Applications/Xcode.app/Contents/Developer/usr/bin
  - /Users/ron/.rvm/bin
  - /Users/ron/.config/yarn/global/node_modules/.bin
  PLATFORM: darwin x64
  FREEMEM: 568143872
  TOTALMEM: 17179869184
  UPTIME: 2342929
  LOADAVG: 2.11328125,2.029296875,2.01513671875
  CPUS:
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  - Intel(R) Core(TM) i7-2635QM CPU @ 2.00GHz - 2000
  ENDIANNESS: LE
  VERSIONS:
  - ares: 1.10.1-DEV
  - cldr: 31.0.1
  - http_parser: 2.7.0
  - icu: 59.1
  - modules: 57
  - nghttp2: 1.25.0
  - node: 8.9.3
  - openssl: 1.0.2n
  - tz: 2017b
  - unicode: 9.0
  - uv: 1.15.0
  - v8: 6.1.534.48
  - zlib: 1.2.11

ERROR Summary:

  - broccoliBuilderErrorStack: [undefined]
  - codeFrame: [undefined]
  - errorMessage: Path must be a string. Received undefined
  - errorType: [undefined]
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
  - message: Path must be a string. Received undefined
  - name: TypeError
  - nodeAnnotation: [undefined]
  - nodeName: [undefined]
  - originalErrorMessage: [undefined]
  - stack: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.join (path.js:1251:7)
    at _migrateAddonInitializers (/Users/ron/mirai-audio/mir/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:92:32)
    at migrateInitializers (/Users/ron/mirai-audio/mir/node_modules/ember-cli-fastboot/lib/build-utilities/migrate-initializers.js:121:3)
    at Class.included (/Users/ron/mirai-audio/mir/node_modules/ember-cli-fastboot/index.js:66:5)
    at project.addons.project.addons.filter.addon (/Users/ron/mirai-audio/mir/node_modules/ember-cli/lib/broccoli/ember-app.js:538:17)
    at Array.filter (<anonymous>)
    at EmberApp._notifyAddonIncluded (/Users/ron/mirai-audio/mir/node_modules/ember-cli/lib/broccoli/ember-app.js:535:47)
    at new EmberApp (/Users/ron/mirai-audio/mir/node_modules/ember-cli/lib/broccoli/ember-app.js:164:10)
    at module.exports (/Users/ron/mirai-audio/mir/ember-cli-build.js:9:13)

=================================================================================
```

Error has been replicated on CircleCI as well:
https://circleci.com/gh/mirai-audio/mir/254

**Comment by 0xadada** [comment]
@kratiahuja could we publish a patch release with this fix?

**Comment by kratiahuja** [comment]
@0xadada doing that now.

**Comment by kratiahuja** [comment]
@0xadada ember-cli-fastboot@1.1.2 is published.
