### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by GarPit** [ember-fastboot/ember-cli-fastboot#603]
After checking index page either in browser or via Curl, I'm getting:

```
TypeError: Cannot read property 'name' of undefined
    at updatePaths (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:29520:1)
    at Class.intermediateTransitionTo (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:28893:1)
    at /Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:29362:1
    at forEachRouteAbove (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:29340:1)
    at error (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:29359:1)
    at Router.triggerEvent (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:29492:1)
    at Object.trigger (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:51087:1)
    at Transition.trigger (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:50900:1)
    at finalizeTransition (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:50129:1)
    at /Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:49536:1
    at tryCatch (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:51502:1)
    at invokeCallback (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:51517:1)
    at publish (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:51485:1)
    at /Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:31279:1
    at invokeWithOnError (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:1000:1)
    at Queue.flush (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:1055:1)
    at DeferredActionQueues.flush (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:863:1)
    at Backburner.end (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:177:1)
    at Backburner.run (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:290:1)
    at Backburner.join (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:319:1)
    at Function.run.join (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/bower_components/ember/ember.debug.js:20614:1)
    at Object.hash.success (/Users/gradus/Projects/meditel_front/tmp/broccoli_merge_trees-output_path-8QeO7DwC.tmp/assets/addon-tree-output/ember-data/adapters/rest.js:622:1)
    at fire (/Users/gradus/Projects/meditel_front/node_modules/jquery-deferred/lib/jquery-callbacks.js:78:30)
    at Object.fireWith (/Users/gradus/Projects/meditel_front/node_modules/jquery-deferred/lib/jquery-callbacks.js:188:7)
    at Object.fire [as resolve] (/Users/gradus/Projects/meditel_front/node_modules/jquery-deferred/lib/jquery-callbacks.js:195:10)
    at dataHandler (/Users/gradus/Projects/meditel_front/node_modules/najax/lib/najax.js:167:13)
    at IncomingMessage.<anonymous> (/Users/gradus/Projects/meditel_front/node_modules/najax/lib/najax.js:198:9)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)```

**Comment by GarPit** [comment]
Sorry, this was "intermediate" error. Final reason is `TypeError: window.scrollTo is not a function`
