### ISSUE TITLE
ReferenceError: document is not defined with Ember source 3.4

### ISSUE THREAD

**Issue by dodeja** [ember-fastboot/ember-cli-fastboot#614]
```
ReferenceError: document is not defined
    at exports.default (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/ember-template-compiler/lib/system/bootstrap.js:31:1)
    at Object.initialize (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/ember-template-compiler/lib/system/initializer.js:24:1)
    at /Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/@ember/engine/index.js:91:1
    at Vertices.each (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/dag-map.js:188:1)
    at Vertices.walk (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/dag-map.js:117:1)
    at DAG.each (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/dag-map.js:62:1)
    at DAG.topsort (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/dag-map.js:68:1)
    at Class._runInitializer (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/@ember/engine/index.js:112:1)
    at Class.runInitializers (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/@ember/engine/index.js:88:1)
    at Class._bootSync (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/@ember/application/lib/application.js:431:1)
    at Class.boot (/Users/akshay/Dev/t49/tnt-ui/tmp/broccoli_merge_trees-output_path-0PsBiH29.tmp/assets/@ember/application/lib/application.js:410:1)
    at EmberApp.buildAppInstance (/Users/akshay/Dev/t49/tnt-ui/node_modules/fastboot/src/ember-app.js:225:21)
    at EmberApp.visitRoute (/Users/akshay/Dev/t49/tnt-ui/node_modules/fastboot/src/ember-app.js:252:17)
    at EmberApp.visit (/Users/akshay/Dev/t49/tnt-ui/node_modules/fastboot/src/ember-app.js:321:17)
    at FastBoot.visit (/Users/akshay/Dev/t49/tnt-ui/node_modules/fastboot/src/index.js:79:22)
    at /Users/akshay/Dev/t49/tnt-ui/node_modules/fastboot-express-middleware/src/index.js:31:14
    at app.use (/Users/akshay/Dev/t49/tnt-ui/node_modules/ember-cli-fastboot/index.js:328:11)
    at Layer.handle [as handle_request] (/Users/akshay/Dev/t49/tnt-ui/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/Users/akshay/Dev/t49/tnt-ui/node_modules/express/lib/router/index.js:317:13)
    at /Users/akshay/Dev/t49/tnt-ui/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/akshay/Dev/t49/tnt-ui/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/akshay/Dev/t49/tnt-ui/node_modules/express/lib/router/index.js:275:10)
    at err (/Users/akshay/Dev/t49/tnt-ui/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/Users/akshay/Dev/t49/tnt-ui/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/Users/akshay/Dev/t49/tnt-ui/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:45:19)
    at invokeCallback (/Users/akshay/Dev/t49/tnt-ui/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:223:31)
    at /Users/akshay/Dev/t49/tnt-ui/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/Users/akshay/Dev/t49/tnt-ui/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by dodeja** [comment]
Error is here 
```
enifed('ember-template-compiler/lib/system/bootstrap', ['exports', 'ember-template-compiler/lib/system/compile'], function (exports, _compile) {
    'use strict';

    /**
      Find templates stored in the head tag as script tags and make them available
      to `Ember.CoreView` in the global `Ember.TEMPLATES` object.
    
      Script tags with `text/x-handlebars` will be compiled
      with Ember's template compiler and are suitable for use as a view's template.
    
      @private
      @method bootstrap
      @for Ember.HTMLBars
      @static
      @param ctx
    */

    /**
    @module ember
    */
    exports.default = function (_ref) {
        var context = _ref.context,
            hasTemplate = _ref.hasTemplate,
            setTemplate = _ref.setTemplate,
            i,
            script,
            templateName,
            template;

        if (!context) {
            context = document;
...
```

**Comment by linearza** [comment]
@dodeja @rwjblue - thanks for pointing us in the right direction, in our case we were using `ember-cli-hot-loader` which seems to have been the culprit

**Comment by allthesignals** [comment]
Seeing this too. I'm going to install `ember-template-compiler` and see if that helps. Here's the trace:

```
ReferenceError: document is not defined
    at Class.getBodyElement (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/labs-zola/initializers/route-css-classes.js:41:1)
    at Class.activate (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/labs-zola/initializers/route-css-classes.js:13:1)
    at Class.superWrapper [as activate] (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/ember-utils.js:308:1)
    at Class.enter (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/ember-routing/lib/system/route.js:354:1)
    at callHook (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/router.js:200:1)
    at _handlerEnteredOrUpdated (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/router.js:1634:1)
    at handlerEnteredOrUpdated (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/router.js:1656:1)
    at setupContexts (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/router.js:1611:1)
    at finalizeTransition (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/router.js:1827:1)
    at /var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/router.js:1514:1
    at tryCatcher (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/rsvp.js:200:1)
    at invokeCallback (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/rsvp.js:372:1)
    at publish (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/rsvp.js:358:1)
    at /var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/ember-testing/lib/ext/rsvp.js:14:1
    at invokeWithOnError (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/backburner.js:256:1)
    at Queue.flush (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/backburner.js:167:1)
    at DeferredActionQueues.flush (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/backburner.js:326:1)
    at Backburner._end (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/backburner.js:748:1)
    at Backburner._boundAutorunEnd (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/backburner.js:483:1)
    at run (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/vendor/babel-polyfill/polyfill.js:4295:1)
    at /var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/vendor/babel-polyfill/polyfill.js:4308:1
    at flush (/var/folders/yl/f4_3rc_92pn_z8zv3hdsg8800000gr/T/broccoli-67116mFcs7jUD6kkw/out-778-broccoli_merge_trees/assets/vendor/babel-polyfill/polyfill.js:1398:1)
```

**Comment by allthesignals** [comment]
> @dodeja - are you including the ember-template-compiler in your generated assets? (from the stack trace it seems that you are)

Sorry - what does this mean exactly? Does this go in fastboot dependencies?

**Comment by dodeja** [comment]
@rwjblue I don't believe so. If it is, I am not sure what would be causing that.

**Comment by lifeart** [comment]
same for https://github.com/lifeart/ember-ast-hot-load/issues/48
@rwjblue any suggestions how to fix it?
