### ISSUE TITLE
TypeError : _emberViewsSystemJquery.default is not a function

### ISSUE THREAD

**Issue by kanishk-anand-oyo** [ember-fastboot/ember-cli-fastboot#657]
I am running ember-cli-fastboot version 1.0.0beta9, and while page renders fine in SSR, it fails due to the able error, with this stack trace : 
```
_emberViewsSystemJquery.default is not a function
    at Class.destroy (/client/dist/fastboot/vendor.js:53456:38)
    at Class.superWrapper [as destroy] (/client/dist/fastboot/vendor.js:32294:22)
    at /client/dist/fastboot/vendor.js:11054:16
    at eachDestroyable (/client/dist/fastboot/vendor.js:11307:9)
    at Container.destroy (/website-v2/client/dist/fastboot/vendor.js:11052:7)
    at Backburner.run (/client/dist/fastboot/vendor.js:10416:25)
    at Object.run [as default] (/client/dist/fastboot/vendor.js:30328:27)
    at Class.willDestroy (/client/dist/fastboot/vendor.js:13627:34)
    at Class.superWrapper [as willDestroy] (client/dist/fastboot/vendor.js:32294:22)
    at invokeWithOnError (/client/dist/fastboot/vendor.js:10075:18)
    at Queue.flush (/client/dist/fastboot/vendor.js:10130:11)
    at DeferredActionQueues.flush (/client/dist/fastboot/vendor.js:9931:17)
    at Backburner.end (/client/dist/fastboot/vendor.js:10309:25)
    at Timeout._onTimeout /client/dist/fastboot/vendor.js:10900:18)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

```

I have tried meeting the dependencies, and installed the ones corresponding to the beta version. I am running the codebase on node 6.9.1 version.

**Comment by rwjblue** [comment]
Something in your app is using `Ember.$(...)` or `this.$(...)` in a fastboot path, it _looks_ like it is happeneing during destruction (based on the stack trace).

What Ember, ember-cli, etc versions are you using?

**Comment by kanishk-anand-oyo** [comment]
Using `ember@2.3.0` , `ember-cli@1.13.15` , `ember-cli-ic-ajax@0.2.4` ,` ember-in-viewport@2.1.1`
