### ISSUE TITLE
Error: Could not find module `~fastboot/app-factory` imported from `(require)` on 2.1.2

### ISSUE THREAD

**Issue by mcfiredrill** [ember-fastboot/ember-cli-fastboot#712]
I got this error after upgrading to 2.1.2, on Ember 3.10.2.

I don't see the error on 2.1.1.

Is there any other information I can provide?
```
Error: Could not find module `~fastboot/app-factory` imported from `(require)`
    at missingModule (/c/Users/mcfir/src/datafruits/tmp/broccoli_persistent_filterfastboot_manifest_rewrite__broccoli_asset_revfastboot_manifest_rewrite-output_path-gmh1et1w.tmp/assets/vendor/loader/loader.js:247:1)
    at findModule (/c/Users/mcfir/src/datafruits/tmp/broccoli_persistent_filterfastboot_manifest_rewrite__broccoli_asset_revfastboot_manifest_rewrite-output_path-gmh1et1w.tmp/assets/vendor/loader/loader.js:258:1)
    at Object.requireModule (/c/Users/mcfir/src/datafruits/tmp/broccoli_persistent_filterfastboot_manifest_rewrite__broccoli_asset_revfastboot_manifest_rewrite-output_path-gmh1et1w.tmp/assets/vendor/loader/loader.js:24:1)
    at Object.<anonymous> (/c/Users/mcfir/src/datafruits/node_modules/fastboot/src/ember-app.js:203:18)
    at VMSandbox.run (/c/Users/mcfir/src/datafruits/node_modules/fastboot/src/vm-sandbox.js:18:15)
    at EmberApp.createEmberApp (/c/Users/mcfir/src/datafruits/node_modules/fastboot/src/ember-app.js:202:30)
    at EmberApp.retrieveSandboxedApp (/c/Users/mcfir/src/datafruits/node_modules/fastboot/src/ember-app.js:227:17)
    at new EmberApp (/c/Users/mcfir/src/datafruits/node_modules/fastboot/src/ember-app.js:61:21)
    at FastBoot._buildEmberApp (/c/Users/mcfir/src/datafruits/node_modules/fastboot/src/index.js:114:17)
    at new FastBoot (/c/Users/mcfir/src/datafruits/node_modules/fastboot/src/index.js:52:10)
    at app.use (/c/Users/mcfir/src/datafruits/node_modules/ember-cli-fastboot/index.js:311:29)
    at Layer.handle [as handle_request] (/c/Users/mcfir/src/datafruits/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/c/Users/mcfir/src/datafruits/node_modules/express/lib/router/index.js:317:13)
    at /c/Users/mcfir/src/datafruits/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/c/Users/mcfir/src/datafruits/node_modules/express/lib/router/index.js:335:12)
    at next (/c/Users/mcfir/src/datafruits/node_modules/express/lib/router/index.js:275:10)
    at err (/c/Users/mcfir/src/datafruits/node_modules/ember-cli/lib/tasks/server/middleware/broccoli-watcher/index.js:54:11)
    at watcher.then (/c/Users/mcfir/src/datafruits/node_modules/broccoli-middleware/lib/watcher-middleware.js:35:7)
    at tryCatcher (/c/Users/mcfir/src/datafruits/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:39:19)
    at invokeCallback (/c/Users/mcfir/src/datafruits/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/-internal.js:211:31)
    at /c/Users/mcfir/src/datafruits/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/then.js:26:14
    at flush (/c/Users/mcfir/src/datafruits/node_modules/ember-cli/node_modules/rsvp/dist/lib/rsvp/asap.js:80:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by MalayaliRobz** [comment]
had the same issue. using version "ember-cli-fastboot": "2.1.0" fixed it for me

**Comment by dnalagatla** [comment]
The Changes causing the issue has been reverted. v2.1.3 should work for production.
