### ISSUE TITLE
Build breaks for a custom app on 2.2.1

### ISSUE THREAD

**Issue by sangm** [ember-fastboot/ember-cli-fastboot#730]
Trying to build our app on `2.2.1`

We are seeing this exception:

```
Restarting BPR processes (pkill -9 -f "renderer.js")
(node:86010) UnhandledPromiseRejectionWarning: Error: Cannot find module '/var/folders/h2/c4_3_zwd0v3298rc7jyl_ljh000gv4/T/broccoli-86010PiEIdOkWFbBv/out-13001-broccoli_merge_trees_merge_build_trees/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Class._updateAppFilesInManifest (foo-project/node_modules/ember-cli-fastboot/index.js:384:17)
    at Class.postBuild (foo-project/node_modules/ember-cli-fastboot/index.js:349:10)
    at addonPromises.project.addons.reduce (foo-project/node_modules/ember-cli/lib/models/builder.js:182:28)
    at Array.reduce (<anonymous>)
    at Builder.processAddonBuildSteps (foo-project/node_modules/ember-cli/lib/models/builder.js:179:43)
    at tryCatcher (foo-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (foo-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (foo-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:481:7)
    at flush (foo-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:86010) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:86010) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:86010) UnhandledPromiseRejectionWarning: Error: Cannot find module '/var/folders/h2/c4_3_zwd0v3298rc7jyl_ljh000gv4/T/broccoli-86010PiEIdOkWFbBv/out-13001-broccoli_merge_trees_merge_build_trees/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Class._updateAppFilesInManifest (foo-project/node_modules/ember-cli-fastboot/index.js:384:17)
    at Class.postBuild (foo-project/node_modules/ember-cli-fastboot/index.js:349:10)
    at addonPromises.project.addons.reduce (foo-project/node_modules/ember-cli/lib/models/builder.js:182:28)
    at Array.reduce (<anonymous>)
    at Builder.processAddonBuildSteps (foo-project/node_modules/ember-cli/lib/models/builder.js:179:43)
    at tryCatcher (foo-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:323:19)
    at invokeCallback (foo-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:495:31)
    at publish (foo-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:481:7)
    at flush (foo-project/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:2402:5)
    at process._tickCallback (internal/process/next_tick.js:61:11)
(node:86010) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

We have two different apps within the same project.

![image](https://user-images.githubusercontent.com/4295680/65303356-a8e5f000-db32-11e9-8c58-77e1e61280a8.png)
![Screen Shot 2019-09-19 at 11 11 31 PM](https://user-images.githubusercontent.com/4295680/65303571-480ae780-db33-11e9-8318-e73bff0ea76d.png)

@dnalagatla has the context here. Would love for you to take a look at it if you have time.

**Comment by kratiahuja** [comment]
@dnalagatla Can we please revert the changes that is causing this issue?

**Comment by dnalagatla** [comment]
> @dnalagatla Can we please revert the changes that is causing this issue?

The PR #737 includes reverts to fix this issue. @kratiahuja can you please help with merging the changes. Thank you.

**Comment by dnalagatla** [comment]
@sangm this ticket can be closed.
