### ISSUE TITLE
Latest master failing for Ember 4.0 Canary

### ISSUE THREAD

**Issue by simonihmig** [ember-fastboot/ember-cli-fastboot#844]
I used the latest master version to make an addon work FastBoot and with Ember 4.0. However the changes in #841 seem to have caused a regression. Getting this:

```
Error: Assertion Failed: Cannot override the computed property `_fastbootInfo` on <dummy@service:fastboot::ember108>.
    at assert (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/debug/index.js:178:1)
    at ComputedProperty.set (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1513:1)
    at initialize (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/system/core_object.js:104:1)
    at Function.create (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/system/core_object.js:674:1)
    at FactoryManager.create (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:527:1)
    at Proxy.create (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:244:1)
    at instantiateFactory (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:342:1)
    at lookup (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:270:1)
    at Container.lookup (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/container/index.js:139:1)
    at Class.lookup (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:81:1)
    at Class.getInjection (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:3561:1)
    at /var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1480:1
    at untrack (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@glimmer/validator.js:836:1)
    at ComputedProperty.get (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1479:1)
    at Class.getter [as fastboot] (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1014:1)
    at getPossibleMandatoryProxyValue (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1919:1)
    at _getProp (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1984:1)
    at _getPath (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:2026:1)
    at get (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1970:1)
    at Class.setURL (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-cli-fastboot/locations/none.js:24:1)
    at Class.superWrapper [as setURL] (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/-internals/utils/index.js:432:1)
    at Class.visit (/var/folders/q3/yzggf_l965zbzps_bk8xr37c0000gn/T/broccoli-13311v3tusXn4uAae/out-330-append_ember_auto_import_analyzer/assets/@ember/application/instance.js:248:1)
    at EmberApp._visit (/Users/simonihmig/Projects/ember-bootstrap/node_modules/fastboot/src/ember-app.js:265:20)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at EmberApp.visit (/Users/simonihmig/Projects/ember-bootstrap/node_modules/fastboot/src/ember-app.js:325:7)
    at FastBoot.visit (/Users/simonihmig/Projects/ember-bootstrap/node_modules/fastboot/src/index.js:86:18)
    at /Users/simonihmig/Projects/ember-bootstrap/node_modules/fastboot-express-middleware/src/index.js:33:20
```

When pulling a previous commit (like https://github.com/ember-fastboot/ember-cli-fastboot/commit/4ad4eeb66bb9d46c0b14b6ed4601a5b5c2de7a5e) then this does *not* happen!

It seems this addon is not using the usual ember-try scenarios to test with different Ember versions, is that correct? 😯

cc @snewcomer

**Comment by gilest** [comment]
This can be closed
