### ISSUE TITLE
Could not find module `@ember/application/deprecations` on Ember 4.1.1

### ISSUE THREAD

**Issue by byteg** [ember-fastboot/ember-cli-fastboot#888]
After adding fastboot to my project I get the following error in my JS console:

`Uncaught Error: Could not find module `@ember/application/deprecations` imported from `ember-cli-fastboot/services/fastboot`
    at vendor-a63d82f2b38476b3b648450a5c71b1d4.js:13:31
    at c (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:13:96)
    at a.findDeps (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:25:158)
    at c (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:13:152)
    at a.findDeps (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:25:158)
    at c (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:13:152)
    at requireModule (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:7:60)
    at s.get (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:6461:153)
    at e._extractDefaultExport (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:6501:128)
    at e.resolveOther (vendor-a63d82f2b38476b3b648450a5c71b1d4.js:6463:18)`

**Comment by MelSumner** [comment]
👋  I'm also having this issue on a new app as well. 

```
Error: Could not find module `@ember/application/deprecations` imported from `ember-cli-fastboot/services/fastboot`
    at missingModule (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/vendor/loader/loader.js:247:1)
    at findModule (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/vendor/loader/loader.js:258:1)
    at Module.findDeps (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/vendor/loader/loader.js:168:1)
    at findModule (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/vendor/loader/loader.js:262:1)
    at Module.findDeps (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/vendor/loader/loader.js:168:1)
    at findModule (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/vendor/loader/loader.js:262:1)
    at requireModule (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/vendor/loader/loader.js:24:1)
    at ModuleRegistry.get (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:28:1)
    at Class._extractDefaultExport (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:464:1)
    at Class.resolveOther (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:124:1)
    at Class.resolve (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/addon-tree-output/ember-resolver/resolvers/classic/index.js:185:1)
    at resolve (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/-internals/container/index.js:954:1)
    at Registry.resolve (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/-internals/container/index.js:659:1)
    at Registry.resolve (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/-internals/container/index.js:662:1)
    at factoryFor (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/-internals/container/index.js:288:1)
    at instantiateFactory (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/-internals/container/index.js:345:1)
    at lookup (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/-internals/container/index.js:278:1)
    at Container.lookup (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/-internals/container/index.js:143:1)
    at Class.lookup (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/-internals/runtime/lib/mixins/container_proxy.js:81:1)
    at Object.patchFetchForRelativeURLs [as initialize] (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/survey-netlify/instance-initializers/setup-fetch.js:16:1)
    at /var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/engine/index.js:140:1
    at Vertices.each (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/dag-map.js:231:1)
    at Vertices.walk (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/dag-map.js:145:1)
    at DAG.each (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/dag-map.js:75:1)
    at DAG.topsort (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/dag-map.js:83:1)
    at App._runInitializer (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/engine/index.js:155:1)
    at App.runInstanceInitializers (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/engine/index.js:138:1)
    at Class._bootSync (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/application/instance.js:110:1)
    at /var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/engine/instance.js:70:1
    at initializePromise (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/rsvp.js:522:1)
    at new Promise (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/rsvp.js:1023:1)
    at Class.boot (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/@ember/engine/instance.js:70:1)
    at /Users/melaniesumner/Code/experiments/survey-netlify/node_modules/fastboot/src/ember-app.js:292:25
    at invokeCallback (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/rsvp.js:495:1)
    at publish (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/rsvp.js:478:1)
    at /var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/ember-testing/lib/ext/rsvp.js:19:1
    at invokeWithOnError (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/backburner.js:360:1)
    at Queue.flush (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/backburner.js:241:1)
    at DeferredActionQueues.flush (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/backburner.js:447:1)
    at Backburner._end (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/backburner.js:999:1)
    at Backburner._boundAutorunEnd (/var/folders/_3/kkhsd8kx2dz4khm6dqk9zqnr0000gq/T/broccoli-37700OMhKv9EU5pjJ/out-338-broccoli_merge_trees/assets/backburner.js:648:1)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ```

**Comment by Windvis** [comment]
It seems ember-cli-fastboot v2 isn't compatible with Ember 4+. [This import path](https://github.com/ember-fastboot/ember-cli-fastboot/blob/114a2ad886c9f1cca4427c5dc67435903c1075be/addon/services/fastboot.js#L2) was [deprecated](https://deprecations.emberjs.com/v3.x#toc_old-deprecate-method-paths) and removed in Ember 4 which is the error message you see here.

I would try using the v3 beta of ember-cli-fastboot which seems to be tested against Ember 4.

**Comment by MelSumner** [comment]
@Windvis this resolved my issue- thanks for pointing it out, I'd pulled down the repo and was trying to figure out why I was getting an error message on an import path that was definitely not in the code I was looking at. 😆

**Comment by byteg** [comment]
Sorry for the stupid question but how can i install the v3 beta?

**Comment by Windvis** [comment]
@byteg You can just modify the version in you package.json file, but v3 has since been [officially released](https://github.com/ember-fastboot/ember-cli-fastboot/releases/tag/v3.2.0) so you can just update to that version instead. I _think_ that should also be the new default if you run `ember install ember-cli-fastboot`.
