### ISSUE TITLE
bug: Fastboot Dependencies Whitelist breaks node_modules resolution expectations

### ISSUE THREAD

**Issue by runspired** [ember-fastboot/ember-cli-fastboot#901]
the effects of this bug are that fastboot cannot be used in conjunction with more recent versions of yarn, pnpm, or pnp strategies that avoid hoisting dependencies to root.

For instance, [ember-fetch](https://github.com/ember-cli/ember-fetch/blob/40867376fdb736b5d6dd7df58a27fbc3cddb09a5/package.json#L100) declares both a `dependency` and whitelistes `abortcontroller-polyfill`. Unless the consuming app also adds `abortcontroller-polyfill` to its dependencies, when hoisting does not occur this will fail to be resolved by the [sandboxedRequire provided by fastboot-schema.js](https://github.com/ember-fastboot/ember-cli-fastboot/blob/703e78832fbb8d4c9d9ace9d9aee6a4e7a72bed5/packages/fastboot/src/fastboot-schema.js#L170) which scopes to the top-level project only.

**Comment by JimSchofield** [comment]
I believe I might be running into this.  Is this is the same issue?

```
Error: Unable to require module 'crypto' because it was not in the whitelist.
    at Object.require (/Users/jschofield/Desktop/prember/node_modules/fastboot/src/fastboot-schema.js:191:15)
    at Module.callback (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:65737:41)
    at Module.exports (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:125:32)
    at Module._reify (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:162:59)
    at Module.reify (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:149:27)
    at Module.exports (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:123:10)
    at Module._reify (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:162:59)
    at Module.reify (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:149:27)
    at Module.exports (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:123:10)
    at Module._reify (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:162:59)
    at Module.reify (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:149:27)
    at Module.exports (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:123:10)
    at requireModule (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:46:18)
    at r (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:195:14)
    at resolveInitializer (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:74840:39)
    at registerInitializers (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:74855:23)
    at loadInitializers (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:74890:5)
    at Module.callback (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/prember.js:37:38)
    at Module.exports (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:125:32)
    at Module._reify (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:162:59)
    at Module.reify (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:149:27)
    at Module.exports (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:123:10)
    at Object.requireModule (/var/folders/sg/lh2rlwc9521_t037mwjj52xh0000gn/T/broccoli-6090qPJkOoP14Y4d/out-284-broccoli_merge_trees/assets/vendor.js:46:18)```
